import json

general_codes = [
("Business & Professions Code","(all sections)","For all violations of the Business and Professions Code","CR"),
("Fish & Game Code","(all sections)","For all violations of the Fish and Game Code, except as listed below","CR"),
("Harbors & Navigation Code","(all sections)","For all violations of the Harbors and Navigation Code","CR"),
("Public Resources Code","(all sections)","For all violations of the Public Resources Code","CR"),
("Welfare & Institutions Code","5150","Certification to Mental Health Courts","CR"),
("CCR Title 14 (Natural Resources)","(all sections)","For all violations of Title 14 of the California Code of Regulations (Natural Resources)","CR"),
("Los Angeles County Code","(all sections)","For all violations of the Los Angeles County Code","CR"),
]

fish_game = [
("Fish & Game Code","2006(a)","Loaded Rifle or Shotgun in Vehicle","BR"),
("Fish & Game Code","3001","Hunting While Intoxicated","BR"),
("Fish & Game Code","3004(a),(b)","Shooting Near Dwelling / Unlawful Discharge of Firearm, Arrow, or Crossbow Bolt Across a Public Road","BR"),
("Fish & Game Code","3004.5(a)(1)","Use of Unlawful Rifle or Pistol Ammunition, Second or Subsequent Offense","BR"),
("Fish & Game Code","4370","Carry Gun During Archery Season","BR"),
]

health = [
("Health & Safety Code","7114","Autopsy Without Authorization","BR"),
("Health & Safety Code","7208","Unlawful Use, Sale or Disposal of Body","BR"),
("Health & Safety Code","11100(g)","Sale/Transfer/Possession of Specified Chemicals, Second or Subsequent","BR"),
("Health & Safety Code","11107.1","Sale/Purchase of Specified Substances, Second or Subsequent","BR"),
("Health & Safety Code","11153","Controlled Substance: Unlawful Prescription","CR"),
("Health & Safety Code","11162.6","Counterfeits/Possesses/Obtains Under False Pretenses or Fraudulently Produces a Controlled Substance Prescription Form","CR"),
("Health & Safety Code","11164","Controlled Substance: Unlawful Prescription Execution/Content","CR"),
("Health & Safety Code","11215","Unlawful Administration of Narcotics","CR"),
("Health & Safety Code","11350","Illegal Possession of Specified Controlled Substances","CR"),
("Health & Safety Code","11352.1","Dispense or Provide Dangerous Drug or Device","CR"),
("Health & Safety Code","11357.5(b)(1)(2)(3)","Use/Possession of Synthetic Cannabinoid Compound/Derivative, Second/Third or Subsequent Offense","CR"),
("Health & Safety Code","11362.81(a)(1)(2)","Medical Marijuana Program - Violation of Specified Provisions, Second Offense","CR"),
("Health & Safety Code","11364.1","Possession of Opium Pipe, Drug Paraphernalia","CR"),
("Health & Safety Code","11366","Maintenance of Place for Disposal of Narcotics","CR"),
("Health & Safety Code","11375.5(b)(1)(2)(3)","Use/Possession of Synthetic Stimulant Compound/Derivative, Second/Third or Subsequent Offense","CR"),
("Health & Safety Code","11377","Possession of Controlled Substance","CR"),
("Health & Safety Code","11395","Possession of Hard Drugs with Two or More Prior Convictions of Sections 11350, 11351, 11351.5, 11352, 11353, 11353.5, 11353.7, 11370.1, 11377, 11378, 11378.5, 11379, 11379.5, 11379.6, 11380, or 11395","MR"),
("Health & Safety Code","11395","...Second or Subsequent Violation","MR"),
("Health & Safety Code","11550","Use or Under the Influence of Controlled Substance","CR"),
("Health & Safety Code","12761","Possession of Flamethrowing Device Without Permit","CR"),
("Health & Safety Code","13002","Littering of Flaming or Glowing Substance","CR"),
("Health & Safety Code","105256","Refuse to Obey Order Regarding Lead Hazard, Second Offense","CR"),
("Health & Safety Code","108240-108290","Hazardous Substances Act Violations","CR"),
("Health & Safety Code","108800-108810","Label Requirements for Containers","CR"),
("Health & Safety Code","110390","Disseminate False Advertisement of Food, Drug, Device or Cosmetic","CR"),
("Health & Safety Code","110395","Manufacture, Sell, Deliver, Hold or Offer for Sale Any Food, Drug, Device or Cosmetic That Is Falsely Advertised","CR"),
("Health & Safety Code","110403(a-an)","Advertise Drug/Device To Have Effect Upon Specified Conditions","CR"),
("Health & Safety Code","110423.2","Sale/Transfer/Furnish a Dietary Supplement Containing Ephedrine Group Alkaloids to a Minor","CR"),
("Health & Safety Code","110620","Manufacture, Sell, Deliver, Hold or Offer for Sale Any Adulterated Food","CR"),
("Health & Safety Code","110625","Adulteration of a Food","CR"),
("Health & Safety Code","110760","Manufacture, Sell, Deliver, Hold or Offer for Sale Any Misbranded Food","CR"),
("Health & Safety Code","110765","Misbranding a Food","CR"),
("Health & Safety Code","110775","Alter, Mutilate, Destroy, Obliterate or Remove Label or Labeling Resulting in Misbranded Food","CR"),
("Health & Safety Code","110960","Hold or Display Any Potentially Hazardous Food Above 45 Degrees Fahrenheit","CR"),
("Health & Safety Code","111295","Manufacture, Sell, Deliver, Hold or Offer for Sale Any Drug or Device That Is Adulterated","CR"),
("Health & Safety Code","111300","Adulteration of a Drug or Device","CR"),
("Health & Safety Code","111550","Sell, Deliver or Give Away New Drug or Device Without Approval by Department","CR"),
("Health & Safety Code","111615","Manufacture a Drug or Device Without a License","CR"),
("Health & Safety Code","111765","Manufacture or Sell a Misbranded Cosmetic","CR"),
("Health & Safety Code","111865","Remove, Sell or Dispose of a Detained or Embargoed Food, Drug, Device or Cosmetic Without Department Permission","CR"),
("Health & Safety Code","112075","Clean, Sterilize and Resell Reusable Bottles Without a License","CR"),
("Health & Safety Code","112400","Operating a Cold Storage or Refrigerating Warehouse Without a License","CR"),
("Health & Safety Code","112505","Operate a Frozen Food Locker Plant Without a License","CR"),
("Health & Safety Code","112550","Failure to Maintain Legal Temperature Limits in a Frozen Food Locker Plant","CR"),
("Health & Safety Code","115215","Radiation Control Law","CR"),
("Health & Safety Code","120280","Refusal to Cooperate with Local Health Officer Quarantine","MR"),
("Health & Safety Code","120290","Willful Exposure to Disease","MR"),
]

penal = [
("Penal Code","69","Obstruct/Resist Public Official by Threats/Violence","MR"),
("Penal Code","71","Threaten Injury to Public Official","MR"),
("Penal Code","76","Threaten Death/Great Bodily Injury to Public Official or Judge","MR"),
("Penal Code","95.1","Threaten Juror","MR"),
("Penal Code","96.5","Obstruction of Justice by Judicial Officer, Commissioner, Referee","CR"),
("Penal Code","112","Manufacture False Government Documents to Conceal Citizenship","CR"),
("Penal Code","131","Misrepresentation in Connection with an Investigation into Specified Corporate Misconduct","CR"),
("Penal Code","135.5","Alter or Destroy Evidence in a Public Safety Officer Disciplinary Proceeding","CR"),
("Penal Code","136.1(a,b)","Witness Intimidation or Tampering","MR"),
("Penal Code","139","Felon Threatening Witness","CR"),
("Penal Code","140","Threaten Witness, Victim or Informant","CR"),
("Penal Code","141(a)","Alter, Plant, Modify, etc. Evidence","CR"),
("Penal Code","146(a)","Arrest or Detain a Person Against His or Her Will","MR"),
("Penal Code","146a(a)","Impersonating an Officer","MR"),
("Penal Code","146g(a-b)","Disclose or Solicit Information for Financial Gain","CR"),
("Penal Code","146g(c)","Disclose or Solicit Unauthorized Photograph or Video","CR"),
("Penal Code","148(a)(1)","Interfere With a Police Officer","CR"),
("Penal Code","148(a)(2)","Interfere, etc., With Transmission of Communication Over a Public Safety Radio Frequency","BR"),
("Penal Code","148(b)","Taking a Weapon From a Police Officer (Non-Firearm)","BR"),
("Penal Code","148(d)","Attempted Taking of Firearm from Police Officer","MR"),
("Penal Code","148.1","Make a False Bomb Report","CR"),
("Penal Code","148.2","Interfere With Emergency Personnel","CR"),
("Penal Code","148.4","Tamper With Fire Alarm, Equipment or False Alarm","CR"),
("Penal Code","148.5","Making a False Report","CR"),
("Penal Code","148.9","Falsely Representing Self as Another Person to a Peace Officer","CR"),
("Penal Code","149","Officer Unnecessarily Assaulting or Beating any Person","MR"),
("Penal Code","151(a)(1)","Advocate Killing/Injuring Peace Officer","CR"),
("Penal Code","152","Conceal or Attempt to Conceal an Accidental Death","CR"),
("Penal Code","152.3","Failure to Notify Peace Officer if Observed Commission of Murder, Rape or Lewd or Lascivious Act by Force or Menace Against a Child Victim Under 14 Years of Age","CR"),
("Penal Code","166(a)(4)","Willful Disobedience of Terms as Written of Any Process or Court Order or Out-of-State Court Order","MR"),
("Penal Code","166(a)(9)","Willful Disobedience of Terms of Any Injunction that Restrains the Activities of a Street Gang","MR"),
("Penal Code","166(c)(1)","Contempt of Court – Violation of Protective Order","MR"),
("Penal Code","166(c)(2)","Contempt of Court – Violation of Protective Order With Injuries","MR"),
("Penal Code","171c/171d","Bring or Possess Loaded Firearms in Specified Offices","CR"),
("Penal Code","171.5","Possession of Weapon Within Sterile Area of Airport","CR"),
("Penal Code","171.7","Possession of Weapon Within Sterile Area of Public Transit Facility","CR"),
("Penal Code","186.22(a)","Participation in Criminal Street Gang Activity","MR"),
("Penal Code","186.28","Supply, Sell, Give Firearm Used in Felony by Criminal Street Gang Member","MR"),
("Penal Code","191.5(b)","Vehicular Manslaughter While Intoxicated Without Gross Negligence","MR"),
("Penal Code","192(c)(1-2)","Vehicular Manslaughter","MR"),
("Penal Code","192.5(b-d)","Vehicular Manslaughter While Operating a Vessel","MR"),
("Penal Code","217.1(a)","Assault on Public Official or Immediate Family of Public Official","MR"),
("Penal Code","236","False Imprisonment","BR"),
("Penal Code","241","Assault","BR"),
("Penal Code","241.5","Assault Committed Against Highway Worker","BR"),
("Penal Code","241.8","Assault on Member of United States Armed Forces","BR"),
("Penal Code","243(a)","Battery","BR"),
("Penal Code","243(b)","Battery on Peace Officer/EMT/Firefighter, etc.","MR"),
("Penal Code","243(c)(1)","Battery on Custodial Officer/EMT/Firefighter, etc. With Injury","MR"),
("Penal Code","243(c)(2)","Battery on Peace Officer with Injury, Simple","MR"),
("Penal Code","243(d)","Battery with Serious Bodily Injury","MR"),
("Penal Code","243(e)","Domestic Battery Without Traumatic Injury","$20,000"),
("Penal Code","243.2","Battery on School, Park, Hospital Property","BR"),
("Penal Code","243.25","Battery Against Elder or Dependent Adult","MR"),
("Penal Code","243.3","Battery on Transit Personnel or Passenger","BR"),
("Penal Code","243.4","Sexual Battery","MR"),
("Penal Code","243.6","Battery on School Employee","BR"),
("Penal Code","243.65","Battery Against Highway Worker","BR"),
("Penal Code","243.7","Battery Against a Juror","MR"),
("Penal Code","243.9","Aggravated Battery by Gassing Peace Officer or Employee of Detention Facility","MR"),
("Penal Code","243.10","Battery Against Member of United States Armed Forces","MR"),
("Penal Code","244.5(b),(c)","Use of Stun Gun or Taser on Any Person","MR"),
("Penal Code","245(a)(1)","Assault With a Deadly Weapon","MR"),
("Penal Code","245(a)(2)","Assault With a Firearm","MR"),
("Penal Code","245(a)(4)","Assault With Force Likely to Produce G.B.I.","MR"),
("Penal Code","245.6(c)","Hazing Without Serious Bodily Injury","BR"),
("Penal Code","245.6(d)","Hazing Resulting in Death or Serious Bodily Injury","MR"),
("Penal Code","246","Shooting at an Occupied Dwelling/Vehicle","MR"),
("Penal Code","246.3","Grossly Negligent Discharge of Firearm or BB Device","MR"),
("Penal Code","247(b)","Shooting at an Unoccupied Dwelling/Vehicle","MR"),
("Penal Code","247.5","Malicious Discharge of Laser at Occupied Aircraft","MR"),
("Penal Code","248","Interfere With Operation of Aircraft","MR"),
("Penal Code","261.5(b)","Unlawful Sexual Intercourse with Minor","CR"),
("Penal Code","261.5(c)","Unlawful Sexual Intercourse with Minor, more than three years younger than perpetrator","BR"),
("Penal Code","261.5(d)","Unlawful Sexual Intercourse with Minor, under 16 years, perpetrator over 21","MR"),
("Penal Code","270","Willful Failure to Provide for Minor Child","CR"),
("Penal Code","270.6","Leave State with Intent to Avoid Spousal Support","CR"),
("Penal Code","271/271a","Fail to Maintain Child Under 14 Years","CR"),
("Penal Code","272(a)(1)","Contribute to the Delinquency of a Minor","CR"),
("Penal Code","272(b)(1)","Communicate With or Contact Minor for Luring or Transporting Minor Away from Home","CR"),
("Penal Code","273a(a)","Child Endangerment with Risk of Great Bodily Injury or Death","MR"),
("Penal Code","273a(b)","Child Endangerment Without Risk of Great Bodily Injury or Death","MR"),
("Penal Code","273d","Cruel or Inhuman Corporal Punishment or Traumatic Injury Upon a Child","MR"),
("Penal Code","273i","Publish Information with Intent that Another Use the Information to Commit Crime Against a Child","MR"),
("Penal Code","273.5","Domestic Battery with Traumatic Injury","$30,000"),
("Penal Code","273.6(a)","Violation of Protective Order if the detained person made threats to kill or harm, has engaged in violence against, or has gone to the residence or workplace of, the protected party","$30,000"),
("Penal Code","273.6(b)","Violation of Protective Order with Injuries","$30,000"),
("Penal Code","273.65","Violation of Dependency Protective Order","MR"),
("Penal Code","273.7","Malicious Disclosure of Trafficking Shelter or Domestic Violence Shelter Location","MR"),
("Penal Code","278","Child Abduction Without Right of Custody","MR"),
("Penal Code","278.5","Child Abduction Depriving Custody or Visitation Right","BR"),
("Penal Code","280","Child Concealment","BR"),
("Penal Code","286(b)(1)","Sodomy With Minor Under 18 Years","MR"),
("Penal Code","287(b)(1)","Oral Copulation with a Minor","MR"),
("Penal Code","288(c)(1)","Lewd/Lascivious Act on Child of 14 or 15 Years","MR"),
("Penal Code","288(c)(2)","Lewd/Lascivious Act on Dependent Person by Caretaker","MR"),
("Penal Code","288.2(a)(1)","Distributes, etc. Harmful Matter Depicting a Minor Engaging in Sexual Conduct with Intent to Seduce","BR"),
("Penal Code","288.2(a)(2)","Harmful Matter Not Depicting a Minor Engaged in Sexual Conduct","BR"),
("Penal Code","288.4(a)(1)","Arrange Meeting With Minor For Purpose of Exposing or Procuring Sexual Exposure or Engaging in Lewd Act","BR"),
("Penal Code","289(c)","Penetration With Foreign Object of Mental Patient by Patient","BR"),
("Penal Code","289(h)","Assist Penetration Act Upon Minor with Foreign Object","MR"),
("Penal Code","289.5","Flee to California to Avoid Prosecution for Sex Offenses","MR"),
("Penal Code","289.6(a)(2-3)","Sexual Activity, as Specified, With Person Confined in Public or Private Detention Facility","MR"),
("Penal Code","290","Failure of Convicted Sex Offender to Register","BR"),
("Penal Code","290.46(j)(1)","Use Information Disclosed on Sex Offender Internet Web Site to Commit a Misdemeanor","BR"),
("Penal Code","290.46(k)","Sex Offender Prohibited from Entering Sex Offender Internet Web Site","MR"),
("Penal Code","290.95(a,b)","Failure to Disclose Sex Offender Status upon Application or Acceptance of Position Involving Minors","BR"),
("Penal Code","290.95(c)","Prohibition on Registered Sex Offender Working with Minors","BR"),
("Penal Code","299.5(i)(1)(A)","Knowingly Use or Disclose Offender Sample or DNA Profile to an Unauthorized Person/Agency for Unauthorized Purpose","BR"),
("Penal Code","299.5(i)(1)(B)","Knowingly and for Financial Gain Use Offender Sample or DNA Profile for Unauthorized Purpose or Disclose DNA or Other Forensic Identification Information to Unauthorized Person/Agency for Unauthorized Purpose","BR"),
("Penal Code","308.1","Import/Distribute/Offer to Sell/Sell to an Unauthorized Person or Business a Tobacco Product Known as \"Beedies\" or \"Bidis\"","BR"),
("Penal Code","311.1","Sale/Distribution of Obscene Matter Depicting a Minor or Containing Digitally-Altered or Artificial-Intelligence-Generated Data Depicting What Appears to be a Minor","BR"),
("Penal Code","311.2(a)","Production/Distribution/Exhibition of Obscene Matter","BR"),
("Penal Code","311.3","Sexual Exploitation of Child","MR"),
("Penal Code","311.4","Employment of Minor in Sale/Distribution of Obscene Matter or Production of Pornography","MR"),
("Penal Code","311.11(a)(1)","Possession or Control of Child Pornography","BR"),
("Penal Code","311.11(a)(2)","Possession or Control of Digitally-Altered or Artificial-Intelligence-Generated Obscene Matter Depicting What Appears to be a Minor","BR"),
("Penal Code","313.1(a-c)","Distribute Harmful Matter to Minor","BR"),
("Penal Code","314(1)","Indecent Exposure","MR"),
("Penal Code","330","Gambling (12 specified games or where there exists a \"bank\")","CR"),
("Penal Code","332","Theft by Trick or Device","CR"),
("Penal Code","337a","Bookmaking","CR"),
("Penal Code","337a(b)","Bookmaking, Second Offense","BR"),
("Penal Code","337a(c)","Bookmaking, Third or Subsequent Offense","BR"),
("Penal Code","337j","Controlled Game","CR"),
("Penal Code","337u","Engage in Acts of Cheating in Gambling Games","CR"),
("Penal Code","337v","Use or Possess Device that Assists in Gambling","CR"),
("Penal Code","337w","Use of Counterfeit Wagering Instruments","CR"),
("Penal Code","337x","Cheat in a Gambling Establishment","CR"),
("Penal Code","337y","Manufacture or Sell Prohibited Device/Mark or Alter Gaming Device/Instruct Another in Cheating","CR"),
("Penal Code","347(b)","False Report of Poisoning food, drink, medicine, pharmaceutical product, or water","CR"),
("Penal Code","368(b)(1)","Elder Abuse with Risk of Great Bodily Injury, Inflicting Pain","BR"),
("Penal Code","368(c)","Elder Abuse without Risk of Great Bodily Injury, Inflicting Pain","CR"),
("Penal Code","368(d)","Elder Abuse without Risk of GBI, Inflicting Pain, Second Offense","MR"),
("Penal Code","368(e)","Theft/Embezzlement, etc. of Elder by Non-caretaker or Caretaker (value not exceeding or exceeding $950)","CR"),
("Penal Code","369g","Drive On or Along Railroad Track or Right of Way","CR"),
("Penal Code","369i","Trespass on Railroad Property","CR"),
("Penal Code","374c","Shooting on a Public Highway","CR"),
("Penal Code","374.2","Malicious Discharge of Toxic Waste Without Permit","CR"),
("Penal Code","374.3(a,b)","Dump or Deposit Waste, Rocks or Dirt on Roads or Highways","CR"),
("Penal Code","374.3(h)","Dump or Deposit Waste in Commercial Quantities","CR"),
("Penal Code","374.7","Littering of Waste in Waters","CR"),
("Penal Code","375(a)-(c)","Discharge of Noxious/Injurious Substance","CR"),
("Penal Code","379","Sale, etc. Salvia Divinorum or Salvinorin A to a Minor","CR"),
("Penal Code","381c","Sell or Furnish a Device or Receptacle Containing Nitrous Oxide to a Minor","CR"),
("Penal Code","399(b)","Keep Mischievous Animal That Causes Serious Bodily Injury","CR"),
("Penal Code","399.5","Owner/Custodian of Dog Trained to Fight, Attack or Kill That Inflicts Substantial Physical Injury or Bites a Human Being on Two Separate Occasions","MR"),
("Penal Code","402","Interfere With Emergency Personnel","BR"),
("Penal Code","404.6(a)","Incitement to Riot","BR"),
("Penal Code","404.6(c)","Incitement to Riot in Prison or Jail, With Serious Bodily Injury","BR"),
("Penal Code","405","Rioting","BR"),
("Penal Code","409","Fail to Disperse from Riot","BR"),
("Penal Code","409.5","Authority of Peace Officers to Close Disaster Area","BR"),
("Penal Code","416","Assembly for Purpose of Disturbing the Peace","CR"),
("Penal Code","417(a)(1)","Brandishing a Deadly Weapon","MR"),
("Penal Code","417(a)(2)","Brandishing a Firearm","MR"),
("Penal Code","417(b)","Brandishing a Firearm at a Daycare Center","MR"),
("Penal Code","417(c)","Brandishing a Firearm in the Presence of a Peace Officer","MR"),
("Penal Code","417.25","Aim or Point a Laser Scope or Pointer at a Person in a Threatening Manner","BR"),
("Penal Code","417.26","Aim or Point a Laser Scope or Pointer at a Peace Officer with Specific Intent to Cause Apprehension or Fear of Bodily Harm","BR"),
("Penal Code","417.4","Brandishing a Fake Firearm","BR"),
("Penal Code","417.6","Brandishing a Deadly Weapon or Firearm with Serious Bodily Injury","MR"),
("Penal Code","422","Criminal Threats","MR"),
("Penal Code","422.3","Threat to Commit Crime Resulting in Death or GBI at Daycare, School, Workplace, House of Worship, or Medical Facility","MR"),
("Penal Code","422.4","Publish Information with Intent that Another Use the Information to Commit A Violent Crime Against an Academic Researcher","BR"),
("Penal Code","422.6","Interference With Civil Rights","BR"),
("Penal Code","422.7","Aggravated Interference with Civil Rights","BR"),
("Penal Code","422.77","Violate Order for Injunctive Relief for Interference with a Person's Free Exercise of a Legal Right or Privilege","BR"),
("Penal Code","423.2(a)","By Force, Threat of Force or Physical Obstruction That Is a Crime of Violence, Attempt to or Intentionally Injure, Intimidate or Interfere With a Reproductive Health Services Client, Provider or Assistant","MR"),
("Penal Code","423.2(b)","By Force, Threat of Force, or Physical Obstruction That Is a Crime of Violence, Attempt to or Intentionally Injure, Intimidate or Interfere With a Person's Lawful Exercise of Religious Freedom at Place of Religious Worship","MR"),
("Penal Code","423.2(c)","By Nonviolent Physical Obstruction, Attempt to or Intentionally Injure, Intimidate or Interfere With a Reproductive Health Services Client, Provider or Assistant, or Intimidate Persons/Entities From Becoming or Remaining the Same","BR"),
("Penal Code","423.2(c)","...Second Offense","BR"),
("Penal Code","423.2(d)","By Nonviolent Physical Obstruction, Attempt to or Intentionally Injure Person's Lawful Exercise of Religious Freedom at Place of Religious Worship","BR"),
("Penal Code","423.2(d)","...Second Offense","BR"),
("Penal Code","423.2(g)","Intentionally Record Reproductive Health Services Patient, Provider, or Assistant Without Consent with Intent to Intimidate Person from Becoming or Remaining a Reproductive Health Services Patient, Provider, or Assistant","BR"),
("Penal Code","423.2(g)","...Second or Subsequent Violation","BR"),
("Penal Code","423.2(h)","Intentionally Disclose or Distribute Unlawful Recording with Intent to Intimidate Person from Becoming or Remaining a Reproductive Health Services Patient, Provider, or Assistant","BR"),
("Penal Code","423.2(h)","...Second or Subsequent Violation","BR"),
("Penal Code","452(a)","Recklessly Causing a Fire with Great Bodily Injury","MR"),
("Penal Code","452(b)","Recklessly Causing a Fire, Inhabited Structure","MR"),
("Penal Code","452(c)","Recklessly Causing Fire, Structure or Forest Land","MR"),
("Penal Code","459","Burglary","BR"),
("Penal Code","459.5","Shoplifting If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","BR"),
("Penal Code","463","Looting","MR"),
("Penal Code","465","Unlawful Entry of a Vehicle","BR"),
("Penal Code","468","Knowingly Buy or Sell Sniperscope","BR"),
("Penal Code","470(d)","Forgery of an Instrument Listed in 473(b) If Value Does Not Exceed $950","CR"),
("Penal Code","475","Forged Bills or Notes, Possession or Receipt If Value Does Not Exceed $950","CR"),
("Penal Code","476","Fictitious Checks, Making, Uttering If Value Does Not Exceed $950","CR"),
("Penal Code","476a","N.S.F. Checks with Aggregate Total That Does Not Exceed $950","CR"),
("Penal Code","483.5(b)","Possess Document-Making Device with Intent to Defraud","CR"),
("Penal Code","488","Petty Theft","CR"),
("Penal Code","487(a),(b)","Petty Theft, Not Qualifying as Shoplifting, If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487a","Petty Theft of Horse or Other Livestock If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487b & 487c","Petty Theft – Conversion of Real Property If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487d","Petty Theft of Gold Dust, Amalgam or Quicksilver If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487f","Petty Theft of Companion Animal If Value Does Not Exceed $950","CR"),
("Penal Code","487g","Petty Theft of Animal for Purpose of Sale, Medical Research, Slaughter or Other Commercial Use If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487h","Petty Theft of Cargo If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487i","Defraud a Housing Program of a Public Housing Authority If Loss Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","487j","Petty Theft of Copper Materials If Value Does Not Exceed $950 and No Disqualifying Prior Conviction(s)","CR"),
("Penal Code","490.4(a)(1-3)","Retail Theft Committed on 2 or More Separate Occasions Within 12-Month Period and Aggregated Value Exceeds $950","CR"),
("Penal Code","490.4(a)(1-3)","Retail Theft Committed in a Manner Not Described Above","CR"),
("Penal Code","490.4(a)(4)","Retail Theft Committed by Recruiting, Coordinating etc. Another to Undertake Specified Acts","CR"),
("Penal Code","490.8","Violation of Retail Theft Restraining Order","CR"),
("Penal Code","496","Receiving Stolen Property with Value Less Than $950 / With Value Exceeding $950","CR"),
("Penal Code","496d","Purchase, Receive, Sell, Stolen/Extorted Vehicles, Vessels or Equipment","CR"),
("Penal Code","496.5","Automotive Property Theft for Resale","CR"),
("Penal Code","502(c)(1-5)","Unlawful Computer Access, Data Usage, Data Damage, Deletion or Alteration, Nonpermitted Use of or Disruption/Denial of Computer Services","BR"),
("Penal Code","502(c)(8)","Unlawful Introduction of Contaminant into Any Computer System/Network","BR"),
("Penal Code","502(c)(10)","Disruption of Government Computer System/Denial/Causing the Denial of Services","BR"),
("Penal Code","502(c)(11)","Add, Alter, Damage, Delete or Destroy Any Data, Computer Software or Computer Programs Associated with a Public Safety Infrastructure Computer, System Network","BR"),
("Penal Code","502(c)(12)","Disruption of Public Safety Infrastructure Computer or Denial or Causing the Denial of Services","BR"),
("Penal Code","502(c)(14)","Introduce Computer Contaminant into Public Safety Infrastructure Computer/System/Network","BR"),
("Penal Code","502.6","Possession or Use of Scanning/Reencoder Device to Access, etc. Information Encoded on Payment Card with Intent to Defraud","CR"),
("Penal Code","528.5","Impersonate Another Person on an Internet Web Site for the Purpose of Harming Another Person","BR"),
("Penal Code","529.7","Obtaining False DMV-Issued Documents","CR"),
("Penal Code","530.5","Misuse of Personal Information","CR"),
("Penal Code","532b(c)(1)","Fraudulently Represent Self as Having Been Awarded Military Decoration with Intent to Obtain Tangible Benefit, Veteran","CR"),
("Penal Code","532b(c)(2)","Fraudulently Represent Self as Having Been Awarded Military Decoration with Intent to Obtain Tangible Benefit","CR"),
("Penal Code","532d","False Statement in Soliciting for Charitable Purpose","CR"),
("Penal Code","532f","Mortgage Fraud","CR"),
("Penal Code","538c","Insert Unauthorized Advertisement into Newspaper for Redistribution","CR"),
("Penal Code","538d(a)","Fraudulent Use of Uniform, Insignia, Emblem, Device, Label Certificate, Card or Writing of Law Enforcement Officer or Impersonation of Law Enforcement Officer by Internet or Other Electronic Means","BR"),
("Penal Code","538d(b)(1-2)","Fraudulent Use of Law Enforcement Officer's Badge","BR"),
("Penal Code","538d(c)","Unlawful Wearing, Using, Making, Selling, Loaning, Giving or Transferring of Law Enforcement Officer's Badge, etc.","BR"),
("Penal Code","538e","Fraudulent Impersonation of a Member of Fire Department or Officer of the State Fire Marshal or Impersonation of Member or Officer by Internet or Other Electronic Means","CR"),
("Penal Code","538g","Fraudulent Impersonation of Public Officer or Employee or Impersonation by Internet or Other Electronic Means","BR"),
("Penal Code","538h","Fraudulent Impersonation of a Government Agency Search and Rescue Unit/Team Officer/Member","BR"),
("Penal Code","538i","Use of Uniform, Insignia, etc. for Fraudulent Impersonation of First Responder during Evacuation Order","BR"),
("Penal Code","591.5","Destruction of Wireless Communication Device to Prevent Summoning Law Enforcement","BR"),
("Penal Code","594(b)(2)(A)","Vandalism, Less Than $400 Damage","CR"),
("Penal Code","594(b)(2)(B)","Vandalism, With a Prior Conviction and Less Than $400 Damage","BR"),
("Penal Code","594.3(a)","Vandalism of a Place of Worship or Cemetery","CR"),
("Penal Code","594.35","Vandalism of Cemetery Grave Markers and Buildings or Interference with Funerals or Interments","CR"),
("Penal Code","594.37","Picketing at a Funeral","CR"),
("Penal Code","594.39","Obstructing, Intimidating, or Harassing Persons at Vaccination Sites","CR"),
("Penal Code","597.6","Declaw Exotic or Native Wild Cat","CR"),
("Penal Code","597b(a)-(b)","Animal Fighting or Cockfighting","CR"),
("Penal Code","597b(c)","Animal Fighting or Cockfighting, Second or Subsequent Offense","BR"),
("Penal Code","597c","Spectator at Animal Fighting Exhibition","CR"),
("Penal Code","597i","Manufacture/Buy/Sale/Possess Gaffs or Slashers","BR"),
("Penal Code","597j","Own/Possess/Train Any Bird or Animal for Fighting Exhibition","CR"),
("Penal Code","597.7","Confine Animal in Unattended Motor Vehicle","CR"),
("Penal Code","599f","Prohibitions Against Non-ambulatory Animals","CR"),
("Penal Code","600.2(c)","Injury or Death of Guide, Signal or Service Dog Caused by Reckless Conduct","CR"),
("Penal Code","600.5(a)","Intentionally Cause Injury to or the Death of Guide, Signal or Service Dog","CR"),
("Penal Code","601","Trespass With Credible Threat","BR"),
("Penal Code","602(h)","Trespass Upon Land Whereon Animals are Being Raised for Human Consumption","BR"),
("Penal Code","602(k)","Trespass to Injure Property/Interfere with Business","CR"),
("Penal Code","602(o)","Refusal to Leave Private Property","CR"),
("Penal Code","602(q)","Refusal to Leave Public Building","CR"),
("Penal Code","602(u)(2)(A)","Enter Restricted Area of Any Airport Operations Area / Passenger Vessel Terminal / Public Transit Facility, Second or Subsequent Offense","BR"),
("Penal Code","602(u)(2)(B)","Refusal to Leave Restricted Area of any Airport / Passenger Vessel Terminal / Public Transit Facility After Request","BR"),
("Penal Code","602(v)(1)","Avoid Inspection When Entering Sterile Area of Airport / Passenger Vessel Terminal / Public Transit Facility, Second or Subsequent Offense","MR"),
("Penal Code","602(v)(2)","Avoid Inspection When Entering Sterile Area of Airport that Causes Delays / Cancellations of Scheduled Flights","BR"),
("Penal Code","602(w)","Trespass to Battered Women's Shelter","CR"),
("Penal Code","602(x)(2)(B)","Refusal to Leave Neonatal Unit After Request to Leave","CR"),
("Penal Code","602(x)(2)(C)","Refusal to Leave Neonatal Unit After Request to Leave, Second or Subsequent Offense","BR"),
("Penal Code","602(y)","Avoid Inspection When Entering Courthouse or Other Governmental Building","CR"),
("Penal Code","602.1","Intentional Interference with Business","CR"),
("Penal Code","602.5(a)","Unauthorized Entry of Dwelling","CR"),
("Penal Code","602.5(b)","Aggravated Trespass","CR"),
("Penal Code","602.9","Rent Skimming","CR"),
("Penal Code","602.12","Trespass on Residential Property of an Academic Researcher for Purpose of Chilling Academic Freedom","CR"),
("Penal Code","602.13","Unlawful Entry into an Animal Enclosure at a Zoo or Circus","CR"),
("Penal Code","626.2","Unauthorized Reentry to School After Suspension or Expulsion with Prior or 415.5 Conviction","CR"),
("Penal Code","626.6","Entry to Campus to Disrupt with Prior or 415.5 Conviction","CR"),
("Penal Code","626.7","Failure to Leave Campus","CR"),
("Penal Code","626.7","Failure to Leave Campus, With Prior or 415.5 Conviction","BR"),
("Penal Code","626.8(a)(1-3)","School Disruption","CR"),
("Penal Code","626.8(a)(4)","School Disruption, With Prior or 415.5 Conviction, or With Intent to Threaten Physical Safety of a Pupil","BR"),
("Penal Code","626.81","Sex Offender on Campus with Prior","BR"),
("Penal Code","626.85","Drug Offender on Campus with Prior or 415.5 Conviction","CR"),
("Penal Code","626.9(f)(2)(B)","Possession of a Firearm on or Within 1,000 Feet from School Grounds","MR"),
("Penal Code","626.95","Firearm or Deadly Weapon on Playgrounds or Youth Centers","MR"),
("Penal Code","626.10","Possession of Dangerous Weapon on School Grounds","BR"),
("Penal Code","636.6(a)","Sale of Signal Jammer, Second or Subsequent Violation","CR"),
("Penal Code","636.6(b)","Operation of Signal Jammer in Conjunction with Commission of Misdemeanor or Felony","BR"),
("Penal Code","636.6(c)","Use of Signal Jammer to Block Public Safety Communications","MR"),
("Penal Code","637.7","Unlawful Use of Electronic Tracking Device","CR"),
("Penal Code","637.9","Prohibited Activities of List Broker re Personal Information of Minors","CR"),
("Penal Code","638.51(a)","Unlawful Use of Pen Register","CR"),
("Penal Code","640(c)(1-3)","Evade Payment of Fare, Misuse Fare Media, or Misuse of Discount Fare, Third or Subsequent Offense","CR"),
("Penal Code","640(d)(1-5)","Willfully Disturb Others, Carry Explosive or Hazardous Substance, Urinate/Defecate, Willfully Block Free Movement of Another Person on or in a System Facility, or Willfully Tamper with or Destroy Any Part of Any Facility or Vehicle of a Transportation System","CR"),
("Penal Code","646.9","Stalking","$50,000"),
("Penal Code","647(b)","Solicit or Engage in Prostitution","BR"),
("Penal Code","647(b)","Solicit or Engage in Prostitution, With Pending 647(b) Charges","BR"),
("Penal Code","647(c)","Accosting Others in Public to Beg/Soliciting Alms","CR"),
("Penal Code","647(e)","Lodging Without Permission","CR"),
("Penal Code","647(f)","Public Intoxication","CR"),
("Penal Code","647(h)","Prowling/Loitering/Wandering on Private Property","CR"),
("Penal Code","647(i)","While Loitering/Prowling/Wandering Upon Private Property, Peek in the Door or Window of an Inhabited Building","BR"),
("Penal Code","647(i)","...Second or Subsequent Offense","MR"),
("Penal Code","647(j)(1)","View by Means of an Instrumentality into Private Area","BR"),
("Penal Code","647(j)(1)","...Second or Subsequent Offense","BR"),
("Penal Code","647(j)(2)","Use Concealed Camcorder or Camera of Any Type to Secretly Tape, Film, Photograph Under/Through the Clothing of a Person with Intent to Arouse","CR"),
("Penal Code","647(j)(3)","Use Concealed Camcorder or Camera of Any Type to Secretly Tape, Film, Photograph in the Interior of a Bedroom, etc. With Intent to Invade Privacy of Another","BR"),
("Penal Code","647(j)(3)","...With Prior Conviction of 647(j)","CR"),
("Penal Code","647(j)(4)","Distribute Private Image or Digitally Created/Altered Image of Intimate Body Part(s) of Another","BR"),
("Penal Code","647(j)(4)","...Second or Subsequent Offense","CR"),
("Penal Code","647(l)","Solicit or Engage in Prostitution with a Minor","BR"),
("Penal Code","647(l)","...With Pending 647(b) or 647(l) Charges","BR"),
("Penal Code","647.6","Child Molestation/Annoying","BR"),
("Penal Code","647.9","Capture of Photographic Image of Deceased Person by First Responder","CR"),
("Penal Code","653b(a)","Loitering About School Grounds","CR"),
("Penal Code","653b(b)","Sex Offender Loitering About School Grounds with Prior","BR"),
("Penal Code","653b(c)","Registered Gang Member Loitering About School Grounds","BR"),
("Penal Code","653c","Sex Offender Entry onto the Grounds of Day Care or Residential Facility for Elders Without Registering with Facility Administrator","BR"),
("Penal Code","653c","...With Prior","MR"),
("Penal Code","653f(a)","Solicitation of Certain Felonies","CR"),
("Penal Code","653f(d)","Solicitation of Drug Offenses","CR"),
("Penal Code","653m","Make Annoying Telephonic or Electronic Contact","CR"),
("Penal Code","653y(b)","Knowing Misuse of 911 Emergency System for Purpose of Harassment, Second or Subsequent Offense","BR"),
("Penal Code","653y(c)","Knowing Misuse of 911 Emergency System for Purpose of Harassment as Hate Crime","CR"),
("Penal Code","653z","Operate Recording Device in Motion Picture Theater","CR"),
("Penal Code","653aa","Electronically Disseminate a Commercial Recording or Audiovisual Work","CR"),
("Penal Code","653.2","Electronically Distribute Personal Identifying Information to Incite Unlawful Action","CR"),
("Penal Code","653.23","Supervise/Recruit/Aid Person in Committing an Act of Prostitution","CR"),
("Penal Code","653.25","Unlawful Loitering for the Purpose of Soliciting Prostitution","BR"),
("Penal Code","666","Petty Theft with Prior Conviction","CR"),
("Penal Code","666.1","Petty Theft or Shoplifting with Two or More Prior Convictions of Sections 211, 215, 368, 487, 487h, 488, 490.2, 459, 459.5, 496, 530.5, or Veh. Code section 10851","MR"),
("Penal Code","666.1","...Second or Subsequent Violation","MR"),
("Penal Code","853.7","Willful Violation of Promise to Appear","CR"),
("Penal Code","1203.2","Warrantless Probation Violation Arrest","MR"),
("Penal Code","1299.11","Noncompliance with the Bail Fugitive Recovery Persons Act","BR"),
("Penal Code","1320","Willful Failure to Appear After Release on Own Recognizance","BR"),
("Penal Code","3003.5","Residing With Another Required to Register as Sex Offender","CR"),
("Penal Code","3003.6","Sex Offender Residing, Working or Volunteering in Facility/Home that Provides Foster Care or is a Placement for a Dependent Child","CR"),
("Penal Code","3010.10","Removal of Electronic, GPS or Other Monitoring Device by One Required to Register as Sex Offender","CR"),
("Penal Code","4501.1","Aggravated Battery by Gassing Officer or Employee of Prison","BR"),
("Penal Code","4532","Escape From Jail, Prison, Industrial Farm, Alternative Custody","MR"),
("Penal Code","4550(b)","Rescue of Prisoner","CR"),
("Penal Code","4570","Communication With Prisoner","CR"),
("Penal Code","4570.5","Fraudulent Entry into Correctional Institute","CR"),
("Penal Code","4575(d)","Possession of Handcuff Key by Inmate","CR"),
("Penal Code","4576","Possession of a Wireless Communication Device w/Intent to Deliver to an Inmate","CR"),
("Penal Code","11166.01(b)","Willful Failure of Mandated Reporter to Report Abuse Where Abuse Results in Death or Great Bodily Injury","CR"),
("Penal Code","11411","Burn or Desecrate Religious Symbol or Hang Noose at School or on Private Property of Another","CR"),
("Penal Code","17500","Possession of Deadly Weapon with Intent to Assault","MR"),
("Penal Code","17510(a)(1)","Carrying Concealed Firearm on Person or in Vehicle While Picketing","CR"),
("Penal Code","17510(a)(2)","Carrying Loaded Firearm on Person or in Vehicle While Picketing","MR"),
("Penal Code","17510(a)(3)","Carrying Deadly Weapon While Picketing","MR"),
("Penal Code","18205","Possession of Firearm or Ammunition in Knowing Violation of TRO","CR"),
("Penal Code","18710","Possession of Destructive Device","CR"),
("Penal Code","18735","Sale, Possession or Transport of Fixed Ammunition - Caliber Greater Than .60 Caliber","CR"),
("Penal Code","19200","Manufacture, Sale, Possession, etc., Metal Military Practice Hand Grenade, Second Offense or Gang-Member","CR"),
("Penal Code","19910","Sale of BB Device, Air or Gas-operated Gun to Minor","BR"),
("Penal Code","19915","Furnishing BB Device, Air or Gas-operated Gun to Minor","CR"),
("Penal Code","20310","Manufacture, Sale, Possession, etc., Air Gauge Knife","CR"),
("Penal Code","20410","Manufacture, Sale, Possession, etc., Belt Buckle Knife","CR"),
("Penal Code","20510","Manufacture, Sale, Possession, etc., Cane Sword","CR"),
("Penal Code","20610","Manufacture, Sale, Possession, etc., Lipstick Case Knife","CR"),
("Penal Code","20710","Manufacture, Sale, Possession, etc., Shobi-zue","CR"),
("Penal Code","20810","Commercially Manufacture/Import/Export/Sale Knives Not Detectable by a Metal Detector","CR"),
("Penal Code","20910","Manufacture, Sale, Possession, etc., Writing Pen Knife","CR"),
("Penal Code","21110","Manufacture, Sale, Possession, etc., Ballistic Knife","CR"),
("Penal Code","21710","Commercially Manufacture/Import/Sale Composite Knuckles or Hard Wooden Knuckles","CR"),
("Penal Code","21810","Manufacture, Sale, Possession, etc., Metal Knuckles","CR"),
("Penal Code","22010","Manufacture, Sale, Possession, etc., Nunchaku","CR"),
("Penal Code","22210","Manufacture, Sale, Possession, etc., Leaded Cane, Billy, Blackjack, Sandbag, Sandclub, Sap or Slungshot","CR"),
("Penal Code","22410","Manufacture, Sale, Possession, etc., Shuriken","CR"),
("Penal Code","22900","Sale, Possession, etc. Tear Gas Weapon","CR"),
("Penal Code","23920","Purchase/Sale/Possession/Transfer Unmarked Firearm","CR"),
("Penal Code","24310","Manufacture, Sale, Possession, etc., Camouflaging Firearm","CR"),
("Penal Code","24410","Manufacture, Sale, Possession, etc., Cane Gun","CR"),
("Penal Code","24510","Manufacture, Sale, Possession, etc., Firearm Not Readily Identifiable","CR"),
("Penal Code","24610","Manufacture, Sale, Possession, etc., Undetectable Firearm","CR"),
("Penal Code","24710","Manufacture, Sale, Possession, etc., Wallet Gun","CR"),
("Penal Code","25100(a)","Criminal Storage of Firearm of First Degree","CR"),
("Penal Code","25100(b)","Criminal Storage of Firearm of Second Degree","CR"),
("Penal Code","25100(c)","Criminal Storage of Firearm of Third Degree","CR"),
("Penal Code","25200(a)","Keep Concealable Firearm, Loaded or Not, Within Premises Under Custody/Control, With Knowledge That Child Under 18 Is Likely to Access, and Child Carries It Off Premises","BR"),
("Penal Code","25200(b)","Concealable Firearm Kept on Any Premises Under Custody/Control With Knowledge That Child Is Likely to Access, and Child Carries It to School or School-sponsored Activity, as Specified","BR"),
("Penal Code","25400","Carrying a Concealed or Concealable Firearm","BR"),
("Penal Code","25850","Carrying a Loaded Firearm in Public","MR"),
("Penal Code","26350","Openly Carrying an Unloaded Handgun in a Public Place, Street, or Vehicle","BR"),
("Penal Code","26400","Carrying Unloaded Firearm on Person Outside of Vehicle","BR"),
("Penal Code","27535","Application to Purchase Within Any 30-day Period More Than One Pistol, Revolver, or Firearm Capable of Being Concealed Upon the Person Prohibited, Third or Subsequent Offense","MR"),
("Penal Code","28215","Falsify Firearm Purchaser Information","BR"),
("Penal Code","29010","License Requirements for Firearm Manufacturer","CR"),
("Penal Code","29180(g)","Possession of Firearm Without Serial Number","MR"),
("Penal Code","29525","Falsify Information on An Entertainment Firearms Permit","CR"),
("Penal Code","29805","Possession of a Firearm by Person Convicted of Specified Misdemeanor or Has Knowledge of an Outstanding Warrant","MR"),
("Penal Code","29815","Possession of a Firearm by Person Prohibited by Probation Condition","MR"),
("Penal Code","29820","Possession of a Firearm by Person Adjudged Ward of Court for Specified Offense","MR"),
("Penal Code","29825","Purchase/Receipt/Ownership/Possession of Firearm by Person Prohibited by TRO, Injunction, or Protective Order","MR"),
("Penal Code","30105(h)","Require Firearms Eligibility Check","CR"),
("Penal Code","30210","Manufacture, Sale, Possession, etc., Ammunition with Flechette Dart or Bullet with Explosive Agent","CR"),
("Penal Code","31360(b)(1)","Prohibited Person with Body Armor","MR"),
("Penal Code","31500","Manufacture, Sale, Possession, etc., Unconventional Pistol","BR"),
("Penal Code","32310(a)","Manufacture, Sale, etc., Large Capacity Magazines","BR"),
("Penal Code","32311","Manufacture, Sale, etc., Large Capacity Magazine Conversion Kits","BR"),
("Penal Code","32900","Manufacture, Sale, Possession, etc., Multiburst Trigger Activator","CR"),
("Penal Code","33215","Manufacture, Sale, Possession, etc., Short-barreled Shotgun or Rifle","CR"),
("Penal Code","33600","Manufacture, Sale, Possession, etc., Zip Gun","CR"),
("Penal Code","33850","Furnish Fictitious Name or Information to Obtain Possession of Firearm in Control of Court or Law Enforcement Agency","CR"),
]

with open("misd_part1.json", "w") as f:
    json.dump({"general": general_codes, "fish_game": fish_game, "health": health, "penal": penal}, f)

print("part1 counts:", len(general_codes), len(fish_game), len(health), len(penal))
