import json

# (code_book, section, description, protocol)
penal = [
("Penal Code","32","Accessories","BR"),
("Penal Code","67","Bribery of State Executive Officer","CR"),
("Penal Code","67.5","Bribery of Public Officer or Employee (if theft or thing given or offered would be grand theft)","CR"),
("Penal Code","68","Bribe, Soliciting by Public Officer or Employee","BR"),
("Penal Code","69","Resisting Arrest/Threatening Executive Officer","MR"),
("Penal Code","76","Threats to the Life of an Official or Judge","MR"),
("Penal Code","92, 93","Bribe, Offering, Accepting by Judge, Juror, Referee","BR"),
("Penal Code","113","Manufacturing or Selling False Citizenship or Resident Alien Documents","CR"),
("Penal Code","114","Using False Documents to Conceal True Citizenship","CR"),
("Penal Code","115","Offering Forged/False Documents for Filing","CR"),
("Penal Code","115.1","Campaign Violations","CR"),
("Penal Code","118","Perjury","CR"),
("Penal Code","127","Subornation of Perjury","CR"),
("Penal Code","136.1(a)(b)","Dissuading a Witness from Testifying","$100,000"),
("Penal Code","136.1(c)","Preventing, Dissuading Witness from Attendance, Testifying","$100,000"),
("Penal Code","137(a),(b)","Influencing Testimony","BR"),
("Penal Code","141(b)","Filing of False Evidence by Police","BR"),
("Penal Code","141(c)","Filing of False Evidence by Prosecuting Attorney","BR"),
("Penal Code","146a(b)","Impersonating an Officer","MR"),
("Penal Code","148(b)","Taking a Weapon from a Peace Officer","MR"),
("Penal Code","148(c)","Taking a Firearm from a Peace Officer","MR"),
("Penal Code","149","Assault by Officer Under Color of Authority","MR"),
("Penal Code","165","Bribery of Councilman, Supervisor, etc.","BR"),
("Penal Code","182","Conspiracy","Same as substantive offense"),
("Penal Code","186.22(a)","Active Participation in Criminal Street Gang","$30,000"),
("Penal Code","187","Murder – with special circumstance","INELIGIBLE FOR RELEASE"),
("Penal Code","187","All other murders","$2,000,000"),
("Penal Code","191.5(a)","Vehicular Manslaughter – DUI with gross negligence","$100,000"),
("Penal Code","191.5(b)","Vehicular Manslaughter – DUI without gross negligence","$50,000"),
("Penal Code","192(a)","Manslaughter – Voluntary","$100,000"),
("Penal Code","192(b)","Manslaughter – Involuntary","$25,000"),
("Penal Code","192(c)(1)","Vehicular Manslaughter – Driving vehicle with gross negligence","$50,000"),
("Penal Code","192(c)(3)","Vehicular Manslaughter – Accident caused for financial gain","$100,000"),
("Penal Code","192.5(a)","Vehicular Manslaughter (Vessel) – DUI with gross negligence","$100,000"),
("Penal Code","192.5(b)","Vehicular Manslaughter (Vessel) – DUI without gross negligence","$50,000"),
("Penal Code","192.5(c)","Vehicular Manslaughter (Vessel) – With gross negligence","$50,000"),
("Penal Code","203","Mayhem","$100,000"),
("Penal Code","205","Aggravated Mayhem (Life)","$1,000,000"),
("Penal Code","207","Kidnapping","$100,000"),
("Penal Code","207 (P.C. 667.85)","Kidnapping child under age 14 to deprive custody","$150,000"),
("Penal Code","207 (P.C. 667.8(a),(b))","Kidnapping for purpose of felony sexual offense","$1,000,000"),
("Penal Code","209","Kidnapping for Ransom, Robbery, Sex Offense, Etc. (Life)","$1,000,000"),
("Penal Code","209.5","Kidnapping During a Carjacking (Life)","$1,000,000"),
("Penal Code","210.5","False Imprisonment – Kidnapping to Evade Arrest","MR"),
("Penal Code","211","Robbery – First Degree","$100,000"),
("Penal Code","211","Robbery – Second Degree","$50,000"),
("Penal Code","215","Carjacking","$100,000"),
("Penal Code","219","Trainwrecking (Life)","$1,000,000"),
("Penal Code","220(a)","Assault with Intent to Commit Mayhem, Rape, Sodomy, Oral Copulation, or Any Violation of P.C. 264.1, 288, or 289","Same as substantive offense"),
("Penal Code","220(b)","Assault with Intent to Commit Specified Sex Offenses While in the Commission of First Degree Burglary","$1,000,000"),
("Penal Code","222","Administering Drugs to Aid Felony","MR"),
("Penal Code","236","False Imprisonment","BR"),
("Penal Code","236.1(a),(b)","Human Trafficking","MR"),
("Penal Code","236.1(c)","If victim is under age 18 and defendant was victim","MR"),
("Penal Code","236.1(c)","If victim is under age 18 and defendant was not victim","$150,000"),
("Penal Code","237(b)","False Imprisonment – Elder or Dependent Person","MR"),
("Penal Code","241.1","Assault – Upon Custodial Officer","BR"),
("Penal Code","243(c)","Battery upon peace officer, etc., with injury","MR"),
("Penal Code","243(d)","Battery – With serious bodily injury","$50,000"),
("Penal Code","243.1","Battery – Upon custodial officer in performance of duties, if arrestee is in custody","BR"),
("Penal Code","243.1","Battery – Upon custodial officer in performance of duties, if arrestee is not in custody","MR"),
("Penal Code","243.4","Sexual Battery","MR"),
("Penal Code","244","Assault with Chemicals","$50,000"),
("Penal Code","244.5(b),(c)","Use of Stun Gun or Taser on Any Person","MR"),
("Penal Code","245(a)(1)","Assault with Deadly Weapon, Other Than a Firearm","$30,000"),
("Penal Code","245(a)(2)","Assault with a Firearm","$30,000"),
("Penal Code","245(a)(4)","Assault with Force Likely to Produce G.B.I.","MR"),
("Penal Code","245(b)","Assault with a Semiautomatic Firearm","$75,000"),
("Penal Code","245(c)","Assault with Deadly Weapon Other Than a Firearm or Force Likely to Produce G.B.I. Upon a Peace Officer or Firefighter","$50,000"),
("Penal Code","245(d)(1)","Assault with a Firearm Upon a Peace Officer or Firefighter","$100,000"),
("Penal Code","245(d)(2)","Assault with a Semiautomatic Firearm Upon a Peace Officer or Firefighter","$200,000"),
("Penal Code","246","Shooting at Inhabited Dwelling, Building, Occupied Motor Vehicle","$250,000"),
("Penal Code","246.3(a)","Discharge of Firearm – Gross Negligence","$35,000"),
("Penal Code","261","Rape","$100,000"),
("Penal Code","261","Rape, if victim is under 18","$200,000"),
("Penal Code","261","Rape, if victim is under 14","$250,000"),
("Penal Code","261.5(c)","Unlawful Sexual Intercourse with Person Under 18","MR"),
("Penal Code","261.5(d)","Unlawful Sexual Intercourse, if defendant is over 21 and minor under 16","MR"),
("Penal Code","264.1","Rape in Concert with Another by Force or Violence","$100,000"),
("Penal Code","264.1","Rape in Concert, if victim is under 18","$200,000"),
("Penal Code","264.1","Rape in Concert, if victim is under 14","$250,000"),
("Penal Code","266h(a)","Pimping","MR"),
("Penal Code","266h(b)(1)","Pimping, if other person is a minor age 16 or older","MR"),
("Penal Code","266h(b)(2)","Pimping, if other person is a minor under age 16","MR"),
("Penal Code","266i","Pandering","BR"),
("Penal Code","266i","Pandering, if other person is a minor","MR"),
("Penal Code","269","Aggravated Sexual Assault of a Child Under 14 Years","$250,000"),
("Penal Code","273a(a)","Willful Harm or Injury to Child Likely to Produce G.B.I. or Death","MR"),
("Penal Code","273d(a)","Corporal Punishment or Injury of Child","MR"),
("Penal Code","273.5","Corporal Injury to Specified Persons","$50,000"),
("Penal Code","273.5 (with prior conviction under 273.5(f))","Corporal Injury to Specified Persons, with prior conviction","$100,000"),
("Penal Code","273.6","Violation of a Protective Order","$50,000"),
("Penal Code","278","Child Stealing","MR"),
("Penal Code","278","Child Stealing, by use of the internet","MR"),
("Penal Code","285","Incest","MR"),
("Penal Code","286(b)(1)","Sodomy, if victim is under age 18","MR"),
("Penal Code","286(b)(2)","Sodomy, if victim is under age 16 and defendant is over age 21","MR"),
("Penal Code","286(c)(1)","Sodomy, if victim is under age 14 and defendant more than 10 years older than victim","$100,000"),
("Penal Code","286(c)(2)(A)","Sodomy, if defendant compelled another by force, duress or threats of great bodily injury","$100,000"),
("Penal Code","286(c)(2)(B)","Sodomy, if victim is under age 14 with force or duress","$100,000"),
("Penal Code","286(c)(2)(C)","Sodomy, if victim is a minor age 14 or older with force or duress","$100,000"),
("Penal Code","286(d)(1)","Sodomy, if in concert with force or fear","$250,000"),
("Penal Code","286(d)(2)","Sodomy, if in concert with force or fear upon a victim under age 14","$250,000"),
("Penal Code","286(d)(3)","Sodomy, if in concert with force or fear upon a minor victim age 14 or over","$250,000"),
("Penal Code","286(e)","Sodomy, if committed in state prison or jail","MR"),
("Penal Code","286(f) and (g)","Sodomy, if victim unconscious of nature of act/incapable of consent","MR"),
("Penal Code","287(b)(1)","Oral Copulation, if victim is under age 18","MR"),
("Penal Code","287(b)(2)","Oral Copulation, if victim is under age 16 and defendant is over age 21","MR"),
("Penal Code","287(c)(1)","Oral Copulation, if victim is under age 14 and defendant more than 10 years older than victim","$100,000"),
("Penal Code","287(c)(2)(A)","Oral Copulation, if defendant compelled another by force, duress or threats of great bodily injury","$100,000"),
("Penal Code","287(c)(2)(B)","Oral Copulation, if victim is under age 14 with force or duress","$100,000"),
("Penal Code","287(c)(2)(C)","Oral Copulation, if the victim is a minor age 14 or older with force or duress","$100,000"),
("Penal Code","287(d)(1)","Oral Copulation, if in concert with force or fear","$250,000"),
("Penal Code","287(d)(2)","Oral Copulation, if in concert with force or fear upon a victim under age 14","$250,000"),
("Penal Code","287(d)(3)","Oral Copulation, if in concert with force or fear upon a minor victim age 14 or over","$250,000"),
("Penal Code","287(e)","Oral Copulation, if committed in state prison or jail and arrestee is in custody","BR"),
("Penal Code","287(e)","Oral Copulation, if committed in state prison or jail and arrestee is out of custody","MR"),
("Penal Code","287(f) and (g)","Oral Copulation, if victim unconscious of nature of act/incapable of consent","MR"),
("Penal Code","288(a)","Lewd Acts, if victim is under age 14","$100,000"),
("Penal Code","288(b)(1)","Lewd Acts, if victim is under age 14 with force","$100,000"),
("Penal Code","288(b)(2)","Lewd Acts, by caretaker upon a dependent person with force","$100,000"),
("Penal Code","288(i)","Lewd Acts, if victim is under age 14 with bodily harm","$1,000,000"),
("Penal Code","288.2","Distribution of Child Pornography","BR"),
("Penal Code","288.2","Distribution of Child Pornography, with prior","MR"),
("Penal Code","288.3(a)","Contact Minor with Intent to Commit Sexual Offense","MR"),
("Penal Code","288.3(c)","Contact Minor with Intent to Commit Sexual Offense, with prior","MR"),
("Penal Code","288.4(a)(2)","Arrange Meeting with Minor for Purpose of Exposing or Procuring Sexual Exposure, with prior","MR"),
("Penal Code","288.4(b)","Attend an Arranged Meeting with Minor for Purpose of Exposing or Procuring Sexual Exposure or Engaging In Lewd Act","MR"),
("Penal Code","288.5","Continuous Sexual Abuse of a Child","$350,000"),
("Penal Code","288.7","Engage in Specified Sex Acts with Minor Under 10","$250,000"),
("Penal Code","289","Sexual Penetration","$100,000"),
("Penal Code","289(a)(1)(B)","Sexual Penetration, if victim is under age 14 with force or duress","$100,000"),
("Penal Code","289(a)(1)(C)","Sexual Penetration, if victim is a minor age 14 or older with force or duress","$100,000"),
("Penal Code","289.6(a)(2)-(3)","Engage in Specified Sex Acts with Person Confined in Public or Private Detention Facility","BR"),
("Penal Code","290-290.024","Failure of Convicted Sex Offender to Register","MR"),
("Penal Code","290.46(j)(2)","Use Information Disclosed on Sex Offender Internet Web Site to Commit a Felony","BR"),
("Penal Code","311.2","Bring or Distribute Obscene Matter Within State","BR"),
("Penal Code","311.4","Use of Minor In Bringing or Distributing Obscene Matter Within State","MR"),
("Penal Code","311.11(a)(1)","Possession or Control of Child Pornography","BR"),
("Penal Code","311.11(a)(2)","Possession or Control of Digitally-Altered or Artificial-Intelligence-Generated Obscene Matter Depicting What Appears to be a Minor","BR"),
("Penal Code","311.11(b)","Possession or Control of Child Pornography, with prior","MR"),
("Penal Code","311.11(c)","Possession or Control of Child Pornography, more than 600 images (with at least 10 images involving prepubescent minor) or images portraying sexual sadism or masochism","MR"),
("Penal Code","314(1)","Indecent Exposure","MR"),
("Penal Code","337a","Bookmaking","CR"),
("Penal Code","337a","Bookmaking, Second Offense","BR"),
("Penal Code","337a","Bookmaking, Third Offense","BR"),
("Penal Code","368(b)(1)","Elder Abuse","MR"),
("Penal Code","368(b)(3)","Elder Abuse Causing Death","MR"),
("Penal Code","368(d)(1)","Elder Abuse, Theft/Embezzlement","MR"),
("Penal Code","405a","Taking Person from Lawful Custody of a Peace Officer By Means of a Riot","MR"),
("Penal Code","422","Criminal Threats","$50,000"),
("Penal Code","422.3","Threat to Commit Crime Resulting in Death or GBI at Daycare, School, Workplace, House of Worship, or Medical Facility","MR"),
("Penal Code","422.6","Interference with Civil Rights","MR"),
("Penal Code","423.2(a)","Second or Subsequent Violation - By Force, Threat of Force or Physical Obstruction That Is a Crime of Violence, Attempt to or Intentionally Injure, Intimidate or Interfere With a Reproductive Health Services Client, Provider or Assistant","MR"),
("Penal Code","423.2(b)","Second or Subsequent Violation - By Force, Threat of Force, or Physical Obstruction That Is a Crime of Violence, Attempt to or Intentionally Injure, Intimidate or Interfere With a Person's Lawful Exercise of Religious Freedom at Place of Religious Worship","MR"),
("Penal Code","423.2(c)","Second or Subsequent Violation - By Nonviolent Physical Obstruction, Attempt to or Intentionally Injure, Intimidate or Interfere With a Reproductive Health Services Client, Provider or Assistant, or Intimidate Persons/Entities From Becoming or Remaining the Same","BR"),
("Penal Code","423.2(d)","Second or Subsequent Violation - By Nonviolent Physical Obstruction, Attempt to or Intentionally Injure Person's Lawful Exercise of Religious Freedom at Place of Religious Worship","BR"),
("Penal Code","423.2(e)","Intentionally Damage/Destroy Property of a Reproductive Services Client, Provider, Assistant or Facility","MR"),
("Penal Code","423.2(f)","Intentionally Damage/Destroy the Property of a Place of Religious Worship","MR"),
("Penal Code","423.2(g)","Second or Subsequent Violation - Intentionally Record Reproductive Health Services Patient with Intent to Intimidate Person from Becoming or Remaining a Reproductive Health Services Patient, Provider, or Assistant","BR"),
("Penal Code","423.2(h)","Second or Subsequent Violation - Intentionally Disclose or Distribute Unlawful Recording with Intent to Intimidate Person from Becoming or Remaining a Reproductive Health Services Patient, Provider, or Assistant","BR"),
("Penal Code","424","Embezzlement or Falsification of Accounts by Public Officers","BR"),
("Penal Code","451(a)","Arson Causing Great Bodily Injury","$250,000"),
("Penal Code","451(b)","Arson, Inhabited Structure","$250,000"),
("Penal Code","451(c)","Arson, Structure or Forest Land","$75,000"),
("Penal Code","451(d)","Arson, Other Property","$50,000"),
("Penal Code","451.5","Aggravated Arson","$500,000"),
("Penal Code","452(a)","Recklessly Causing Fire with Great Bodily Injury","$35,000"),
("Penal Code","452(b)","Recklessly Causing Fire, Inhabited Structure","$25,000"),
("Penal Code","452(c)","Recklessly Causing Fire, Structure or Forest Land","$20,000"),
("Penal Code","453(a)","Possession, Etc. of Explosives, Flammable Matter","$50,000"),
("Penal Code","454","Arson During State of Emergency","$350,000"),
("Penal Code","455","Attempt or Preparation to Burn Any Structure or Property","$75,000"),
("Penal Code","459","Burglary – Residential, First Degree with Person Present (a non-1270.1(a)(1) crime)","$50,000"),
("Penal Code","459","Burglary – Inhabited Dwelling, no Person Present","MR"),
("Penal Code","459","Burglary – All Others","BR"),
("Penal Code","463","Looting","MR"),
("Penal Code","464","Burglary With Explosives","MR"),
("Penal Code","465","Unlawful Entry of a Vehicle","BR"),
("Penal Code","470","Forgery","BR"),
("Penal Code","470a","Forgery/Counterfeiting Driver's License or I.D. Card","BR"),
("Penal Code","470b","Displaying or Possessing Forged Driver's License or I.D. Card With Intent to Accomplish a Forgery","BR"),
("Penal Code","471","Forgery, False Entries in Records or Returns","CR"),
("Penal Code","472","Forgery or Counterfeiting Any Public or Corporate Seal","CR"),
("Penal Code","475","Forged Bills or Notes, Possession or Receipt","CR"),
("Penal Code","476","Fictitious Checks, Making, Uttering","CR"),
("Penal Code","476a","N.S.F. Checks","CR"),
("Penal Code","477, 479, 480","Counterfeiting of Coin","CR"),
("Penal Code","484b","Theft, Diversion of Money Received For Services, Labor, Material, Etc. If Amount Diverted Exceeds $2,350","CR"),
("Penal Code","484c","Embezzlement Of Funds for Construction","CR"),
("Penal Code","484e - 484i","Various Felonies Relating to Credit Cards","BR"),
("Penal Code","487(a) and (b)","Grand Theft If Value Exceeds $950, Or with Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487(c)","Grand Theft Person","MR"),
("Penal Code","487(d)(1)","Theft of Automobile","BR"),
("Penal Code","487(d)(1)","Theft of Automobile, when there is evidence of a chop shop operation","BR"),
("Penal Code","487(d)(2)","Grand Theft – Firearm","$50,000"),
("Penal Code","487a","Grand Theft of Horse or Other Livestock If Value Exceeds $950, or with Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487b","Grand Theft – Conversion of Real Property If Value Exceeds $950, or With Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487d","Grand Theft of Gold Dust, Amalgam or Quicksilver If Value Exceeds $950, or With Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487e","Grand Theft of Companion Animal If Value Exceeds $950","BR"),
("Penal Code","487g","Grand Theft of Animal for Purpose of Sale, Medical Research, Slaughter or Other Commercial Use If Value Exceeds $950, or With Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487h","Grand Theft of Cargo If Value Exceeds $950, or With Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487i","Defraud a Housing Program of a Public Housing Authority of Value Exceeding $950, or with Qualifying Prior Conviction(s) If Value Does Not Exceed $950","BR"),
("Penal Code","487j","Grand Theft of Copper Materials If Value Exceeds $950, or With Qualifying Prior Conviction(s) If Value Does Not Exceed $950","CR"),
("Penal Code","487m","Grand Theft of Wages If Value Exceeds $950 From One Employee, or If Value Exceeds $2,350 In Aggregate from Two or More Employees In Any Consecutive 12-Month Period","CR"),
("Penal Code","490.4","Organized Retail Theft","BR"),
("Penal Code","496","Receiving Stolen Property If Value More Than $950, or With Qualifying Priors If Value Does Not Exceed $950","CR"),
("Penal Code","496.5","Automotive Property Theft for Resale","CR"),
("Penal Code","497","Stolen Property, Bringing into State","CR"),
("Penal Code","502","Computer Related Crimes","BR"),
("Penal Code","502(c)(1)-(7)","Unlawful Access, Data Usage/Damage/Deletion/Alteration, Nonpermitted Use, Denial of Service","BR"),
("Penal Code","502(c)(8)","Introduction of a Contaminant","MR"),
("Penal Code","502(c)(10)-(14)","Government Computer System or Public Safety Infrastructure","MR"),
("Penal Code","504","Embezzlement, Misappropriation by Public Officers","BR"),
("Penal Code","504a","Embezzlement, Disposal of Personal Property Under Lease or Lien","CR"),
("Penal Code","504b","Embezzlement of Proceeds of Sale of Secured Property","BR"),
("Penal Code","505","Embezzlement by Carrier or Individual Transporting for Hire","CR"),
("Penal Code","506","Embezzlement, Misappropriation by Trustee, Contractor","CR"),
("Penal Code","507","Embezzlement by Bailee","CR"),
("Penal Code","514","Embezzlement or Defalcation of Public Funds","CR"),
("Penal Code","518, 519","Extortion, Not Amounting to Robbery","CR"),
("Penal Code","522","Extortion, Obtaining Signature by Threats","CR"),
("Penal Code","523(a)","Extortion, Threatening Letters","CR"),
("Penal Code","523(b)","Extortion, Ransomware","MR"),
("Penal Code","529","False Personation of Another","BR"),
("Penal Code","530.5","Unauthorized Use of Personal Information to Obtain Credit, Goods, etc.","BR"),
("Penal Code","532","False Pretenses","CR"),
("Penal Code","532f","Mortgage Fraud","BR"),
("Penal Code","538i","Use of Uniform, Insignia, etc. for Fraudulent Impersonation of First Responder during Evacuation Order","BR"),
("Penal Code","548","Defrauding Insurer","CR"),
("Penal Code","550","False or Fraudulent Insurance Claim","BR"),
("Penal Code","594(b)(1)","Vandalism, Damage of $400 or More","BR"),
("Penal Code","594.3(b)","Church/Cemetery Vandalism","BR"),
("Penal Code","597","Cruelty to Animals","MR"),
("Penal Code","597.5(a)","Dog Fighting","BR"),
("Penal Code","636.6(c)","Use of Signal Jammer to Block Public Safety Communications","MR"),
("Penal Code","646.9(a)-(c)","Stalking","$150,000"),
("Penal Code","647(b)","Solicit or Engage in Prostitution Where Victim was Under 16, or Under 18 and a Human Trafficking Victim","MR"),
("Penal Code","647(b)","Solicit or Engage in Prostitution (as above), Second or Subsequent Violation","MR"),
("Penal Code","647(j)(3)","Second or Subsequent Violation Where Victim is a Minor and Offender is 18 or Older, Use Concealed Camcorder or Camera of Any Type to Secretly Tape, Film, Photograph in the Interior of a Bedroom, etc. With Intent to Invade Privacy of Another","BR"),
("Penal Code","647.6","Child Molestation with Specified Prior","$150,000"),
("Penal Code","653f(b)","Solicit Murder","MR"),
("Penal Code","653f(c)","Solicit Rape, etc.","MR"),
("Penal Code","653w(a)","Failure to Disclose Origin of Recording or Audiovisual Work","BR"),
("Penal Code","664(a)","Attempt Where Completed Crime Punishable by State Prison (except attempted murder)","Same as substantive offense"),
("Penal Code","664/187","Attempted Murder","$1,000,000"),
("Penal Code","666","Petty Theft, With qualifying prior conviction(s)","BR"),
("Penal Code","666.1","Petty Theft or Shoplifting with Two or More Prior Convictions of Sections 211, 215, 368, 487, 487h, 488, 490.2, 459, 459.5, 496, 530.5, or Veh. Code section 10851","MR"),
("Penal Code","666.1","Petty Theft or Shoplifting with Two or More Priors, Second or Subsequent Violation","MR"),
("Penal Code","4501","Assault with Deadly Weapon by Prison Inmate","$25,000"),
("Penal Code","4501.5","Battery on Non-Inmate by Prison Inmate, if arrestee is in custody","BR"),
("Penal Code","4501.5","Battery on Non-Inmate by Prison Inmate, if arrestee is not in custody","MR"),
("Penal Code","4502","Possession of Deadly Weapon by Prison Inmate, if arrestee is in custody","BR"),
("Penal Code","4502","Possession of Deadly Weapon by Prison Inmate, if arrestee is out of custody","MR"),
("Penal Code","4503","Holding of Hostages by Prison Inmate","$100,000"),
("Penal Code","4530","Escape, Attempted Escape from Prison with or Without Force or Violence","MR"),
("Penal Code","4532","Escape, Attempted Escape by Felon, Misdemeanant, Inebriate, or Person on Work Furlough from Jail, Industrial Farm, etc.","MR"),
("Penal Code","4573","Bringing Controlled Substance into Jail or Prison","CR"),
("Penal Code","4574","Bringing Weapon into Jail or Prison","BR"),
("Penal Code","11418(b) (except (b)(2))","Possession, Etc. Weapons of Mass Destruction","$500,000"),
("Penal Code","11418(b)(2)","Employ Weapon of Mass Destruction – Cause Death (Life)","$1,000,000"),
("Penal Code","11418.1","Send, Etc. False Weapon of Mass Destruction with Intent to Cause Fear","MR"),
("Penal Code","11419","Possession of Biological Agents","MR"),
("Penal Code","18715","Possession of Destructive Devices or Explosives in Public Places","MR"),
("Penal Code","18720","Possession of Materials with Intent to Make Destructive Device or Explosive","MR"),
("Penal Code","18725","Carry or Place Explosive on Common Carrier","MR"),
("Penal Code","18740","Possession of Exploding or Destructive Device or Explosive with Intent to Injure","$500,000"),
("Penal Code","18745","Exploding Destructive Device or Explosive with Intent to Murder (Life)","$1,000,000"),
("Penal Code","18750","Unlawful Explosion Causing Bodily Injury","$500,000"),
("Penal Code","22810","Unlawful Use of Tear Gas","MR"),
("Penal Code","25400","Concealed Weapon on Person or in Vehicle","MR"),
("Penal Code","25850","Possession of a Loaded Firearm","MR"),
("Penal Code","26100(c)","Personally Shooting From Motor Vehicle","$250,000"),
("Penal Code","29800","Concealable Firearms, Ownership or Possession by Felon, Addict; Knowledge of Outstanding Warrant","MR"),
("Penal Code","30305(a)","Unlawful Possession of Ammunition","MR"),
("Penal Code","30600","Manufacture, Distribute, Etc. Assault Weapon","MR"),
("Penal Code","30605","Possession of Any Assault Weapon","MR"),
("Penal Code","31360(a)","Felon with Body Armor","MR"),
("Penal Code","33410","Possession of Silencer","MR"),
]

vehicle = [
("Vehicle Code","2800.2","Attempting to Evade Peace Officer, Reckless Driving","MR"),
("Vehicle Code","2800.3(a)","Attempting to Evade Peace Officer, Causing serious bodily injury","$100,000"),
("Vehicle Code","2800.3(b)","Attempting to Evade Peace Officer, Causing death","$150,000"),
("Vehicle Code","2800.4","Attempting to Evade Peace Officer, Driving in opposite direction of lawfully moving traffic","MR"),
("Vehicle Code","4463","Ownership Certificate, License Forgery","BR"),
("Vehicle Code","10801","Own or Operate a Chop Shop","BR"),
("Vehicle Code","10851(a)","Driving Car Without Consent","CR"),
("Vehicle Code","10851(b),(e)","Driving Car Without Consent, Specified vehicles, P.C. 666.5 prior","BR"),
("Vehicle Code","20001","Hit And Run: Personal Injury","BR"),
("Vehicle Code","23152","Driving Under the Influence of Alcohol or Drugs if a felony per V.C. 23550 or 23550.5","MR"),
("Vehicle Code","23153","Driving Under the Influence of Alcohol or Drugs Causing Bodily Injury","MR"),
("Vehicle Code","23153","Driving Under the Influence of Alcohol or Drugs Causing Bodily Injury, with Personal Infliction of GBI on Any Person Other Than an Accomplice, or Personal Use of a Dangerous or Deadly Weapon","$100,000"),
]

health = [
("Health & Safety Code","443.17(a)","Knowingly Altering or Forging, or Concealing or Destroying Withdrawal or Rescission of, Request For Aid-In-Dying Drug to End Life","BR"),
("Health & Safety Code","443.17(b)","Knowingly Coercing or Exerting Undue Influence to, or Destroying Withdrawal or Rescission of, Request For Aid-In-Dying Drug to End Life","BR"),
("Health & Safety Code","11152, 11153","Controlled Substances, Writing, Dispensing Prescription","CR"),
("Health & Safety Code","11154, 11155","Controlled Substances, Prescribing, Administering, Furnishing","BR"),
("Health & Safety Code","11156","Controlled Substances, Prescribing, Administering, Furnishing to Addict","BR"),
("Health & Safety Code","11162.5(a)","Counterfeiting Prescription Blank","CR"),
("Health & Safety Code","11350","Illegal Possession of Certain Specific or Classified Controlled Substances With Qualifying Prior Conviction(s)","BR"),
("Health & Safety Code","11350.5","Possession of GHB With Intent to Commit Sexual Assault","MR"),
("Health & Safety Code","11351","Possession or Purchase For Sale of Certain Specific or Classified Controlled Substances","BR"),
("Health & Safety Code","11351.5","Possession or Purchase For Sale of Cocaine Base","BR"),
("Health & Safety Code","11352","Illegal Transportation, Sale, Furnishing of Certain Specific or Classified Controlled Substances","BR"),
("Health & Safety Code","11353","Person 18 Years or Over Using Minor in Sale, Transportation, or Giving to a Minor Certain Specific or Classified Controlled Substances, up to 1 kilogram","$50,000"),
("Health & Safety Code","11353","...if over 1 kilogram","$100,000"),
("Health & Safety Code","11353","...if over 4 kilograms","$250,000"),
("Health & Safety Code","11353","...if over 10 kilograms","$500,000"),
("Health & Safety Code","11353","...if over 20 kilograms","$1,000,000"),
("Health & Safety Code","11353","...if over 40 kilograms","$2,000,000"),
("Health & Safety Code","11353","...if over 80 kilograms","$5,000,000"),
("Health & Safety Code","11353.5","Adult Preparing to Sell to Minor Drugs or Narcotics","BR"),
("Health & Safety Code","11354","Person Under 18 Years Using Minor in Sale, Transportation, or Giving to a Minor Certain Specific or Classified Substances","BR"),
("Health & Safety Code","11355","Sale or Furnishing Substance Falsely Represented as Controlled Substance, With Respect to Certain Specific or Classified Controlled Substances","BR"),
("Health & Safety Code","11358","Marijuana: Cultivate, Process","BR"),
("Health & Safety Code","11359","Marijuana, Possession For Sale","BR"),
("Health & Safety Code","11360(a)","Marijuana: Transportation, Sale, Furnishing","BR"),
("Health & Safety Code","11361","Marijuana: Person 18 Years or Over Using Minor Under 14 in Sale, Transportation, Giving to Minor","BR"),
("Health & Safety Code","11362.3(a)(6)","Manufacture Concentrated Cannabis Using Volatile Solvent Without License","BR"),
("Health & Safety Code","11363","Peyote: Cultivating, Processing","BR"),
("Health & Safety Code","11366","Maintain Place for Selling, Giving, Using of Certain Specific or Classified Controlled Substance","BR"),
("Health & Safety Code","11366.5(a)","Rent, Lease, Etc. Room For Manufacture, Storage or Distribution of Controlled Substance","BR"),
("Health & Safety Code","11366.5(b)","Allowing Location To Be Fortified For Sale","BR"),
("Health & Safety Code","11366.6","Using Fortified Location For Sale","BR"),
("Health & Safety Code","11368","Narcotic Drug: Forging, Altering Prescription","CR"),
("Health & Safety Code","11370.1","Possession of Specified Controlled Substances While Armed With a Loaded Firearm","MR"),
("Health & Safety Code","11377","Possession of Controlled Substances with Qualifying Prior Conviction(s)","MR"),
("Health & Safety Code","11377.5","Possession of Controlled Substances with Intent to Commit Sexual Assault","MR"),
("Health & Safety Code","11378","Possession of Controlled Substances For Sale","BR"),
("Health & Safety Code","11378.5","Possession or Purchase For Sale Of PCP","BR"),
("Health & Safety Code","11379","Sale of Controlled Substances","BR"),
("Health & Safety Code","11379.5","Sale of PCP","BR"),
("Health & Safety Code","11379.6","Manufacture of Any Controlled Substance","MR"),
("Health & Safety Code","11380","Soliciting Minor Re Controlled Substances, if 2,000 pills or less","$50,000"),
("Health & Safety Code","11380","...if 2,001 – 5,000 pills","$75,000"),
("Health & Safety Code","11380","...if 5,001 or more pills","$100,000"),
("Health & Safety Code","11382","Sale Substance Represented to Be Controlled Substance","BR"),
("Health & Safety Code","11383","Possession With Intent to Manufacture PCP","BR"),
("Health & Safety Code","11383","Possession With Intent to Manufacture Methamphetamine or N-Ethylamphetamine","BR"),
("Health & Safety Code","11383","Possession With Intent to Sell, Transfer or Furnish Specified Chemicals to Another Person Having Intent to Manufacture PCP","BR"),
("Health & Safety Code","11383","Possession With Intent to Sell, Transfer or Furnish Specified Chemicals to Another Person Having Intent to Manufacture Methamphetamine or N-Ethylamphetamine","BR"),
("Health & Safety Code","11395","Possession of Hard Drugs with Two or More Prior Convictions of Sections 11350, 11351, 11351.5, 11352, 11353, 11353.5, 11353.7, 11370.1, 11377, 11378, 11378.5, 11379, 11379.5, 11379.6, 11380, or 11395","MR"),
("Health & Safety Code","11395","...Second or Subsequent Violation","MR"),
]

bp = [
("Business & Professions Code","22449","Price Gouging in Connection with Dream Act Applications","BR"),
]

enhancements = [
("Sentence Enhancement (PC)","186.22(b)","GANGS – Any felony for the benefit of a street gang","$40,000"),
("Sentence Enhancement (PC)","12022(b)(1),(2)","WEAPONS – Personal use of a Weapon Other Than Firearm","$20,000"),
("Sentence Enhancement (PC)","12022(a)(1),(2),12022(c),(d),12022.2,12022.3,12022.4,12022.5,12022.53(b)","Offense Involved Possession/Use/Discharge of Firearm","$50,000"),
("Sentence Enhancement (PC)","12022.53(c)","Personal Discharge of Firearm Not Causing GBI","$200,000"),
("Sentence Enhancement (PC)","12022.53(d),12022.55","Personal Discharge of Firearm Causing GBI or Death","$1,000,000"),
("Sentence Enhancement (PC)","186.11","Aggravated White Collar Crime Enhancement (Multiple Felonies Involving Fraud or Embezzlement)","MR"),
("Sentence Enhancement (PC)","236.4,12022.7,12022.8,12022.9","INJURY – Infliction of Great Bodily Injury","$30,000"),
("Sentence Enhancement (Health & Saf. Code)","11356.5","NARCOTICS – Inducing Another to Commit Large-Scale Narcotics Offense","$30,000"),
("Sentence Enhancement (Health & Saf. Code)","11370.4","Additional terms for possession for sale, transportation, or conspiracy to possess for sale or transport of controlled substances, based on weight","$10,000"),
("Sentence Enhancement (PC)","667.5(c),1192.7(c),1192.8,667(a)(1),667.51(a),667.6(a),667.10(a)","PRIOR CONVICTIONS – Prior Conviction for Serious/Violent (\"Strike\") or Enumerated Sex Offense","$50,000 per prior"),
("Sentence Enhancement (PC)","667.5(c),1192.7(c),1192.8,667.51(c),667.6(b)","Current Serious/Violent (\"Strike\") or Enumerated Sex Offense with Two or More Prior Convictions for Serious/Violent or Sex Offenses","$1,000,000"),
("Sentence Enhancement (PC)","667.5(b)","Defendant Served a Prior Prison Term for a Sexually Violent Offense Within the Past Five Years","$10,000 per prior"),
("Sentence Enhancement (PC)","368(b)(2)","OTHER – Elder Abuse","$25,000"),
("Sentence Enhancement (PC)","422.7, 422.75","Felony that is a Hate Crime","MR"),
("Sentence Enhancement (PC)","667.9, 667.10","Specified Offenses Against Victim Over 65, Under 14, Disabled","$25,000"),
("Sentence Enhancement (PC)","12022.1","Felony Offense Committed While Felony Charges Pending Against Defendant, or Defendant on Parole or Felony Probation, or Probation Department Supervision","$25,000"),
("Sentence Enhancement (PC)","12022.6","Taking, Damaging, or Destroying Property in Commission or Attempted Commission of a Felony","$10,000"),
("Sentence Enhancement (PC)","12022.10","Sale, Exchange, or Return of Stolen Property","BR"),
("Sentence Enhancement (PC)","12022.65","Acting in Concert with Two or More Persons to Take, Attempt to Take, Damage, or Destroy Property in the Commission or Attempted Commission of a Felony","MR"),
("Sentence Enhancement (PC)","667.61, 667.7, 667.71","Any Enhancement, Not Otherwise Listed in This Schedule, Which Carries a Possible Term of Life Imprisonment","$1,000,000"),
]

all_entries = []
for lst in [penal, vehicle, health, bp, enhancements]:
    for code_book, section, desc, protocol in lst:
        all_entries.append({
            "type": "felony",
            "code": code_book,
            "section": section,
            "description": desc,
            "protocol": protocol,
        })

with open("felony.json", "w") as f:
    json.dump(all_entries, f, indent=1)

print(f"Felony entries: {len(all_entries)}")
