import json

vehicle = [
("Vehicle Code","20","False Statements","CR"),
("Vehicle Code","31","False Statements to Peace Officer","CR"),
("Vehicle Code","1808.45","Unauthorized Disclosure of DMV Records","CR"),
("Vehicle Code","2468(a)","Failure of Licensed Renderer to Keep Written Records of Inedible Kitchen Grease","CR"),
("Vehicle Code","2468(b)","Refusal of Licensed Renderer or Registered Transporter to Exhibit Required Record or Destruction of Required Record","CR"),
("Vehicle Code","2800(a)","Refusal to Obey Peace Officer","BR"),
("Vehicle Code","2800(b)","Refusal to Comply With Peace Officer's Out-of-Service Order","BR"),
("Vehicle Code","2800(c)","Refusal to Comply With U.S. Secretary of Department of Transportation's Out-of-Service Order","BR"),
("Vehicle Code","2800.1(a,b)","Fleeing Peace Officer Prohibited","MR"),
("Vehicle Code","2800.2(a)","Evade Peace Officer - Disregard for Safety","MR"),
("Vehicle Code","2800.3","Evade Peace Officer - Causing Death or Great Bodily Injury","MR"),
("Vehicle Code","2800.4","Driving Opposite to Direction of Lawfully Moving Traffic While Fleeing Peace Officer","MR"),
("Vehicle Code","2801","Refusal to Obey Firefighter Prohibited","CR"),
("Vehicle Code","2803(a)","Refusal to Adjust Unsafe or Unlawful Load","BR"),
("Vehicle Code","2803(b)","Failure to Submit Weight Certificate or Bill of Lading to Officer","BR"),
("Vehicle Code","2813","Commercial Vehicle Inspection","CR"),
("Vehicle Code","2813.5(b)","Use or Issuance of Unauthorized Inspection Stickers","CR"),
("Vehicle Code","4461(b)","Unlawful Lending/Use of Disabled Person Placard","CR"),
("Vehicle Code","4461(c)","Unlawful Display of Disabled Person Placard","CR"),
("Vehicle Code","4461(d)","Unlawful Use of Special Identification Plate","CR"),
("Vehicle Code","4462.5","Unlawful Display of Evidence of Registration With Intent to Avoid Compliance","CR"),
("Vehicle Code","4463(b)(1-3),(c)","Unlawful Forgery, Passing, Possession, Sale or Display of Disabled Person Placard With Fraudulent Intent","CR"),
("Vehicle Code","5506","Resell/Transfer of Total Loss Salvage Vehicle","CR"),
("Vehicle Code","5753(a-d)","Failure of Commercial Dealer to Deliver Certificate of Ownership and Registration Card to Transferee","CR"),
("Vehicle Code","5753(f)","Failure of Licensed Dealer Upon Written Request to Disclose Pertinent Information","CR"),
("Vehicle Code","5901","Notice by Dealer, etc. of Transfer or Mileage","CR"),
("Vehicle Code","8802","Failure to Return Evidence of Registration to DMV Upon Cancellation, Suspension, or Revocation When Committed With Intent to Defraud","CR"),
("Vehicle Code","8804","Resident Registering Vehicle in Foreign Jurisdiction","CR"),
("Vehicle Code","9872","Defacing, Destroying or Altering Hull Identification Number","CR"),
("Vehicle Code","9872.1(a)","Knowingly Buy, Sell or Possess Altered/Destroyed Hull Identification Number","CR"),
("Vehicle Code","10501(a)","False Report of Vehicle Theft With Intent to Deceive","CR"),
("Vehicle Code","10750(a)","Unauthorized Alteration of Vehicle Numbers or Identification Marks","CR"),
("Vehicle Code","10751(a)","Knowing Purchase, Sale, or Possession of Vehicle With Removed, Defaced, Altered, or Destroyed Registration or Identification","CR"),
("Vehicle Code","10851(a)","Taking or Driving Vehicle Without Consent","CR"),
("Vehicle Code","10851.5","Theft of Binder Chains","CR"),
("Vehicle Code","10852","Injuring or Tampering With Vehicle or Contents Without Consent of Owner","CR"),
("Vehicle Code","10853","Climbing Onto, Attempting to Manipulate, or Tampering With Unattended Vehicle With Intent to Commit Malicious Injury","CR"),
("Vehicle Code","10854","Tampering With, Driving, or Removing any Part of Vehicle by Bailee","CR"),
("Vehicle Code","11500","Conducting Business as Automobile Dismantler Without Valid Permit/License and Official Place of Business","CR"),
("Vehicle Code","11515(a,b,d,e)","Salvage Vehicle Notice and Certificate Requirements","CR"),
("Vehicle Code","11520(a)","Failure of Licensed Auto Dismantler to Provide Required Notice to DMV and DOJ Within Required Time","CR"),
("Vehicle Code","11700","Acting as Dealer, Remanufacturer, Manufacturer, Transporter, or Distributor Without A Valid License","CR"),
("Vehicle Code","11713(a-t)","Engage in Prescribed Unlawful Acts by a Licensed Manufacturer, Transporter or Dealer","CR"),
("Vehicle Code","11713.17(a,b)","Violation by Dealer, Manufacturer, or Distributor of Requirements for Securing Front License on Vehicle","CR"),
("Vehicle Code","11725(a)","Removal of Vehicle to Foreign Jurisdiction for Registration","CR"),
("Vehicle Code","11725(b)","Failure to Remove License Plates From Vehicle if Known That Vehicle Is to be Exported to Foreign Jurisdiction","CR"),
("Vehicle Code","11800","Conduct of Business as Vehicle Salesperson Without Valid License","CR"),
("Vehicle Code","12110(a)","Providing or Requesting a Commission, Gift or Compensation in Consideration of Arranging or Requesting the Services of a Tow Truck","CR"),
("Vehicle Code","12110(c)","Exchange of Valuable Consideration Between Towing Service or Employee of Towing Service and Repair Shop or Employee of Repair Shop for the Delivery or Arranging of Delivery of a Vehicle for Storage or Repair","CR"),
("Vehicle Code","12500(a)","Unlawful to Drive Unless Licensed (No License)","CR"),
("Vehicle Code","12515(b)","Minor Under 21 Employed to Drive in Interstate Commerce or Carry Hazardous Materials","CR"),
("Vehicle Code","12517(a)(2)","Operation of School Bus Without Certificate in Possession While Transporting Pupils","CR"),
("Vehicle Code","12517(b)","Operation of School Pupil Activity Bus Without Certificate in Possession While Transporting Pupils","CR"),
("Vehicle Code","12517.45(a)","Unlawful Operation of Specified Vehicle Transporting Pupils","CR"),
("Vehicle Code","12519(a)","Farm Labor Vehicle License","CR"),
("Vehicle Code","12951(b)","Refusal to Present License to Officer","CR"),
("Vehicle Code","13004(a-g)","Identification Card - Unlawful Use","CR"),
("Vehicle Code","13004.1(a)","Manufacture or Sale of Fraudulent I.D.","CR"),
("Vehicle Code","14601(a)","Driving When Privilege Suspended or Revoked","CR"),
("Vehicle Code","14601.1(a)","Driving When Privilege Suspended or Revoked for Offenses Not Relating to Driving Ability","CR"),
("Vehicle Code","14601.2(a,b)","Driving When Privilege Suspended or Revoked for Driving Under Influence of Alcohol/Drugs","CR"),
("Vehicle Code","14601.3(a)","Accumulation of Driver Record History by Habitual Traffic Offender During Period of License Suspension or After Revocation","CR"),
("Vehicle Code","14601.4(a)","Causing Bodily Injury While Driving with Suspended or Revoked License","BR"),
("Vehicle Code","14601.5(a,b)","Driving When Privilege Suspended or Revoked for Refusing Chemical Test or Driving with Excessive Blood Alcohol","CR"),
("Vehicle Code","14601.5","...Second Offense (Section 14601, 14601.2, 14601.3, 14601.5 Within 5 Years)","CR"),
("Vehicle Code","14604(a)","Knowingly Allow Another to Drive Vehicle Without Valid Driver's License","CR"),
("Vehicle Code","14610(a)(1-8)","Unlawful Use of License","CR"),
("Vehicle Code","14610.1(a)","Manufacture or Sale of Fraudulent I.D./Driver's License Prohibited","CR"),
("Vehicle Code","15501","Presentation of False Driver's License by Minor","CR"),
("Vehicle Code","16030(a)","Knowingly Provide False Evidence of Financial Responsibility","CR"),
("Vehicle Code","16560(a,b)","Violation of Interstate Highway Carrier Requirements","CR"),
("Vehicle Code","20001(a)","Duty to Stop When Involved in Accident With Injury or Death","CR"),
("Vehicle Code","20002(a,b)","Hit and Run - Property Damage","CR"),
("Vehicle Code","20003","Failure to Provide Required Information or Render Necessary Assistance to Occupants of Struck Vehicle With Accident Resulting in Injury or Death","CR"),
("Vehicle Code","21200.5","Bicyclist Riding Under the Influence","CR"),
("Vehicle Code","21464(d)","Willful Interference With Traffic Device or Willful Use, Possession, or Distribution of Traffic Interference Device That Results in Injury or Death","CR"),
("Vehicle Code","21651(b)","Wrong Way Driving","CR"),
("Vehicle Code","21651(c)","Wrong Way Driving With Injury or Death","CR"),
("Vehicle Code","21655.9(c)","Operate or Own Vehicle That Displays Low-Emission Decal Not Issued for the Vehicle","CR"),
("Vehicle Code","21702(a,b)","Limitation on Driving Hours","CR"),
("Vehicle Code","21713","Armored Car Without License","CR"),
("Vehicle Code","21963","Blind Pedestrians - Right of Way","CR"),
("Vehicle Code","22406.1","Maximum Speed for Commercial Vehicles, In Excess of Speed Limit by 15 MPH or More","CR"),
("Vehicle Code","22513(b)","Stop to Solicit Towing Services","BR"),
("Vehicle Code","22513(c)","Towing Without Authorization","BR"),
("Vehicle Code","22520.5(a)","Vending on Freeway Right-of-Way (Second Offense)","CR"),
("Vehicle Code","22658","Failure of Tow Company or Driver on Request by Owner or Owner's Agent to Release Vehicle Removed from Private Property Not Yet in Transit","CR"),
("Vehicle Code","23103(a,b)","Reckless Driving","CR"),
("Vehicle Code","23104(a,b)","Reckless Driving – Bodily Injury","BR"),
("Vehicle Code","23105(a)","Reckless Driving – Specific Injury","BR"),
("Vehicle Code","23109(a)","Engaging in Speed Contests","CR"),
("Vehicle Code","23109(b)","Abetting Speed Contests","CR"),
("Vehicle Code","23109(c)","Engaging in or Abetting Exhibition of Speed","CR"),
("Vehicle Code","23109(d)","Placing Barricades or Obstructions","CR"),
("Vehicle Code","23109(e)(2)","Engaging in Speed Contest and Causing Bodily Injury","BR"),
("Vehicle Code","23109(f)(1)","Engaging in Speed Contest With Prior","BR"),
("Vehicle Code","23109(f)(2)","Engaging in Speed Contest and Causing Bodily Injury With Prior","MR"),
("Vehicle Code","23109.1","Engaging in Speed Contest – Specific Injury","BR"),
("Vehicle Code","23110(a)","Throwing Substance at Vehicle Prohibited","CR"),
("Vehicle Code","23112.5(a)","Hazardous Materials - Notification of Agency","CR"),
("Vehicle Code","23114(a,b,e,f)","Spilling Load on Highway Prohibited (Second or Subsequent Offense Within 2 Years)","BR"),
("Vehicle Code","23127","Unauthorized Motor Vehicle on Riding/Hiking Trails","CR"),
("Vehicle Code","23152","Driving Under Influence of Alcohol and/or Drugs","BR"),
("Vehicle Code","23152 w/ 23572","...Special Allegation: Minor in Vehicle","BR"),
("Vehicle Code","23152 w/ 23578","...Special Allegation: BAC Greater Than .15% or Refusal","BR"),
("Vehicle Code","23152 w/ 23580","...Special Allegation: Two or More Prior Convictions Within 10 Years","MR"),
("Vehicle Code","23152 w/ 23582","...Special Allegation: Excessive Speed (> 30 freeway; > 20 street)","BR"),
("Vehicle Code","23153","Driving Under Influence Causing Injury","MR"),
("Vehicle Code","23153 w/ 23578","...Special Allegation: BAC Greater Than .15% or Refusal","MR"),
("Vehicle Code","23153 w/ 23580","...Special Allegation: Two or More Prior Convictions Within 10 Years","MR"),
("Vehicle Code","23153 w/ 23582","...Special Allegation: Excessive Speed (> 30 freeway; > 20 street)","MR"),
("Vehicle Code","23224(a,b)","Possession of Alcohol by Minor In a Vehicle Prohibited","CR"),
("Vehicle Code","23247(a)","Unlawful to Rent/Loan Vehicle to Person With License Restriction Requiring Ignition Interlock Device","CR"),
("Vehicle Code","23247(b-e)","Unlawful to Request/Solicit Someone to Blow Into Device/Start Motor Vehicle With Device; to Drive Unequipped Vehicle; Tamper With Vehicle Requiring Interlock Device","CR"),
("Vehicle Code","23253","Failure to Obey CHP or DOT Officers at Vehicular Crossing","CR"),
("Vehicle Code","23332","Trespass on Vehicular Crossing","CR"),
("Vehicle Code","23573(i)","Willful Failure to Install Ignition Interlock Device Within Required 30 Days","BR"),
("Vehicle Code","24002.5(a)","Unlawful Operation of a Farm Labor Vehicle","CR"),
("Vehicle Code","24011.3(c)(1)","Passenger Vehicle Manufacturer - Willful Failure to Affix Bumper Strength Notice or Willful Misstatement of Information in the Notice","CR"),
("Vehicle Code","24011.3(c)(2)","Willful Defacement, Alteration or Removal of New Vehicle Bumper Strength Notice Prior to Delivery of the Vehicle","CR"),
("Vehicle Code","27150.1","Sale of Exhaust Systems Restricted","CR"),
("Vehicle Code","27362(a)","Sale or Installation of Non-Conforming Child Restraint System","CR"),
("Vehicle Code","28050","Advertisement, Sale, Use or Installation of Device Causing Motor Vehicle Odometer to Register Mileage Other Than True Mileage Driven","CR"),
("Vehicle Code","28050.5","Operation of Motor Vehicle Knowing the Odometer Is Disconnected or Nonfunctional with Intent to Defraud","CR"),
("Vehicle Code","28051","Disconnecting, Turning Back or Resetting Odometer of Motor Vehicle","CR"),
("Vehicle Code","28051.5","Advertisement, Sale or Use of Device Designed for Purpose of Turning Back or Resetting Odometer to Reduce Mileage","CR"),
("Vehicle Code","28150(d)","Possession of Four or More Radar Jamming Devices","CR"),
("Vehicle Code","31303(b-e)","Violating Requirements for Transportation of Hazardous Waste","CR"),
("Vehicle Code","31401(b)","Farm Labor Buses and Trucks - Inspection Required","CR"),
("Vehicle Code","31401(d)","Willful Rental or Use of Farm Labor Vehicle by Owner or Contractor Without CHP Inspection per VC 31401(b)","CR"),
("Vehicle Code","31402(a)","Operation of Unsafe Farm Labor Vehicle","CR"),
("Vehicle Code","31403","Mechanic Certification of Farm Labor Vehicle","CR"),
("Vehicle Code","31602(a-c)","License, Routes to Be Used, Stopping Specified","CR"),
("Vehicle Code","31607(a)","Inspection Required","CR"),
("Vehicle Code","31609","Record of Inspection","CR"),
("Vehicle Code","31610(a-e)","Improper Equipment, Maintenance","CR"),
("Vehicle Code","31611","Improper/Lack of Maps of Route","CR"),
("Vehicle Code","31612","Carry and Display Shipping Instructions","CR"),
("Vehicle Code","31613","Prohibited Cargoes","CR"),
("Vehicle Code","31614(a,b,d,e,h)","Transport Explosives Through Local Routes; Congested Areas; With Enclosed, Uncovered Loads; While Smoking or Open Flame","CR"),
("Vehicle Code","31614(c,g)","Loading Explosives Without Motor Stopped, Brakes Set; Vehicle Transporting Explosives Left Unattended","CR"),
("Vehicle Code","31614(f,i)","Driving Near or Through Fires; Transportation of Explosives in a Passenger Vehicle","CR"),
("Vehicle Code","32000.5(a)","Hazardous Materials Transportation - Company Not Licensed","CR"),
("Vehicle Code","32000.5(d)","Fireworks Transportation - Failure to Carry License or Present","CR"),
("Vehicle Code","32001(c)","Hazardous Material - Motor Carrier Directing Transportation Unlawfully","CR"),
("Vehicle Code","32002(a)","Violations of Division 14.1 or Regulations, Unlicensed Transportation","CR"),
("Vehicle Code","32002(b)","...Second or Subsequent Offense","CR"),
("Vehicle Code","33000","Violation of Shipment Regulations for the Transportation of Radioactive Materials","CR"),
("Vehicle Code","34100","Illegal Operation of Tank Vehicle Transporting Hazardous Waste or Flammable and Combustible Liquids on a Public Highway","CR"),
("Vehicle Code","34501(e)","Operation of Bus Without Current Inspection by CHP","CR"),
("Vehicle Code","34501.3(a)(2)","Motor Carriers - Unlawful Schedule Exceeding Maximum Hours of Service","CR"),
("Vehicle Code","34505(a-c)","Violation of Tour Bus Inspection and Repair Requirements","CR"),
("Vehicle Code","34505.5(a-c)","Violation of Motor Carrier Vehicle Inspection and Repair Requirements","CR"),
("Vehicle Code","34505.9(a)(4)(D)","Violation of Intermodal Roadability Inspection Program","CR"),
("Vehicle Code","34506(a)","Failure to Comply with Specified Regulation of Hours of Service of Drivers","CR"),
("Vehicle Code","34506(b)","Failure to Comply with Specified Regulation of Hazardous Material Transportation","CR"),
("Vehicle Code","34506(c)","Failure to Comply with Specified Regulation of School Buses","CR"),
("Vehicle Code","34506(d)","Failure to Comply with Specified Regulation of Youth Buses","CR"),
("Vehicle Code","34506(e)","Failure to Comply with Specified Regulation of Tour Buses","CR"),
("Vehicle Code","34506(f)","Failure to Comply with Specified Regulation of Described Vehicles","CR"),
("Vehicle Code","34506(g)","Failure to Comply with Specified Regulation of School Pupil Activity Buses","CR"),
("Vehicle Code","34623(h)","Motor Carrier of Property Operating Vehicle While Permit Suspended","CR"),
("Vehicle Code","34623(i)(1)","Motor Carrier of Property with Suspended Permit Allowing Any Vehicles Subject to Suspension Based on Failure to Maintain to be Operated by Another Carrier","CR"),
("Vehicle Code","34623(i)(2)","Motor Carrier of Property Knowingly Utilizing a Vehicle From a Motor Carrier Whose Permit Is Suspended Based on a Failure to Maintain Any Vehicle","CR"),
("Vehicle Code","35784(b)","Violation of Special Permit Requirements","CR"),
("Vehicle Code","35784.5(a)","Transportation of Extra-legal Load Without Permit","CR"),
("Vehicle Code","35785(b)","Violation of Single Saw Log Hauling Speed Limit of 15 MPH Over Bridge or Causeway or 25 MPH on Highway","CR"),
("Vehicle Code","35786(b)","Operation of Truck Booster Power Unit in Noncompliance with Route Specifications","CR"),
("Vehicle Code","35790(g)","Failure to Carry Appropriate Permits, Certificates, and Notices Required for Movement of Manufactured Homes","CR"),
("Vehicle Code","35790(h)","Violation of Terms, Conditions, or Limitations Specified in Manufactured-Home Transportation Permits","CR"),
("Vehicle Code","38316(a)","Reckless Driving of Off-Highway Motor Vehicle","CR"),
("Vehicle Code","38317","Reckless Driving of Off-Highway Motor Vehicle Causing Injury","CR"),
("Vehicle Code","38318(a)","Throwing Substance at Off-Highway Motor Vehicle","CR"),
("Vehicle Code","38318.5","Malicious Removal or Alteration of Markers or Signs","CR"),
("Vehicle Code","38319","Operation of Off-Highway Motor Vehicle Likely to Cause Damage","CR"),
("Vehicle Code","38320(a,b)","Throwing, Depositing or Dumping Matter","CR"),
("Vehicle Code","40001(c)","Violation by Employer of Out-of-Service Order","CR"),
("Vehicle Code","40001(d)","Employer Allows, Permits, Requires, or Authorizes Driver to Operate Commercial Motor Vehicle in Violation of Railroad-Highway Grade Crossing Statute or Regulation","CR"),
("Vehicle Code","40005","Employer Undertakes Responding to Employee Driver's Citation and Inaction By Employer Results in Issuance of Warrant For Employee","CR"),
("Vehicle Code","40008(a)","Violation of VC 21701, 21703, or 23103 with Intent to Capture Physical Impression of Another Person for Commercial Purpose","CR"),
("Vehicle Code","40008(b)","Violation of VC 21701, 21703, or 23103 with Intent to Capture Physical Impression of Another Person and Causing Endangerment of Minor","CR"),
("Vehicle Code","40504(b)","Signing Written Promise to Appear With False Name","CR"),
("Vehicle Code","40508(a-c)","Violation of Promise to Appear, Promise to Pay (In Addition to the Bail on Original Offense)","CR"),
("Vehicle Code","40519(c)","Failure to Appear at Time of Trial After Pleading Not Guilty in Writing","CR"),
("Vehicle Code","40614","Use of Fictitious Name","CR"),
("Vehicle Code","40616","Violation of Promise to Correct","CR"),
("Vehicle Code","42005(e)","Failure to Attend Traffic Violator School","CR"),
("Vehicle Code","(Speed Violations)","1 to 15 Miles Over Limit","CR"),
("Vehicle Code","(Speed Violations)","16 to 25 Miles Over Limit","CR"),
("Vehicle Code","(Speed Violations)","26 and Above (Miles Over Limit)","CR"),
("Vehicle Code","42009 (Highway Construction Zones)","1 to 15 Miles Over Limit","CR"),
("Vehicle Code","42009 (Highway Construction Zones)","16 to 25 Miles Over Limit","CR"),
("Vehicle Code","42009 (Highway Construction Zones)","26 and Above (Miles Over Limit)","CR"),
]

with open("misd_part1.json") as f:
    part1 = json.load(f)

all_entries = []
for lst_name in ["general", "fish_game", "health", "penal"]:
    for code_book, section, desc, protocol in part1[lst_name]:
        all_entries.append({"type":"misdemeanor","code":code_book,"section":section,"description":desc,"protocol":protocol})

for code_book, section, desc, protocol in vehicle:
    all_entries.append({"type":"misdemeanor","code":code_book,"section":section,"description":desc,"protocol":protocol})

with open("misdemeanor.json", "w") as f:
    json.dump(all_entries, f, indent=1)

print("Misdemeanor entries:", len(all_entries))

# combine with felony
with open("felony.json") as f:
    felony = json.load(f)

combined = felony + all_entries
with open("bail_data.json", "w") as f:
    json.dump(combined, f, indent=1)

print("Total combined entries:", len(combined))
